SELECT * FROM SNOTAETAPA WHERE
SNOTAETAPA.RA = '0027336'
AND SNOTAETAPA.TIPOETAPA = 'N'
AND IDTURMADISC  = 11933

SELECT COUNT (SPROVAS.CODPROVA) as TOTALDEPROVA
FROM SPROVAS (NOLOCK) 
WHERE SPROVAS.CODETAPA = 1 
  AND SPROVAS.CODCOLIGADA = 3
  AND SPROVAS.IDTURMADISC = 11933

SELECT COUNT (SNOTAS.CODPROVA) AS TOTALDEPROVAALU
FROM SNOTAS (NOLOCK)
WHERE SNOTAS.CODETAPA = 1
  AND SNOTAS. CODCOLIGADA = 3
  AND SNOTAS.IDTURMADISC = 11933
  AND SNOTAS.RA = '0027336'
  /*AND SNOTAS.NOTA IS NOT NULL*/
  

SELECT 

ST.CODFILIAL,
SMC.DESCRICAO,
ST.CODTURMA,
STURNO.NOME,
SPLETIVO.CODPERLET,
ST.DTINICIAL

FROM STURMA ST

INNER JOIN SHABILITACAOFILIAL SHF ON
	SHF.CODCOLIGADA = ST.CODCOLIGADA 
AND SHF.IDHABILITACAOFILIAL = ST.IDHABILITACAOFILIAL
AND SHF.CODFILIAL = ST.CODFILIAL

INNER JOIN SGRADE ON 
	SGRADE.CODCOLIGADA = SHF.CODCOLIGADA 
AND SGRADE.CODCURSO = SHF.CODCURSO 
AND SGRADE.CODHABILITACAO = SHF.CODHABILITACAO 
AND SGRADE.CODGRADE = SHF.CODGRADE

INNER JOIN SCURSO ON 
SCURSO.CODCOLIGADA = SGRADE.CODCOLIGADA
AND SCURSO.CODCURSO = SGRADE.CODCURSO

INNER JOIN SMODALIDADECURSO SMC ON
	SMC.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO
AND SMC.CODCOLIGADA = SCURSO.CODCOLIGADA

INNER JOIN STURNO ON 
	STURNO.CODCOLIGADA = SHF.CODCOLIGADA 
AND STURNO.CODTURNO = SHF.CODTURNO

INNER JOIN SPLETIVO ON 
	SPLETIVO.CODCOLIGADA = ST.CODCOLIGADA 
AND SPLETIVO.IDPERLET = ST.IDPERLET

WHERE ST.DTINICIAL IS NULL
AND ST.CODCOLIGADA = 3



SELECT DISTINCT SALUNO.RA FROM SALUNO
INNER JOIN SMATRICPL ON 
	SMATRICPL.CODCOLIGADA = SALUNO.CODCOLIGADA 
AND SMATRICPL.RA = SALUNO.RA
WHERE
SALUNO.CODCOLIGADA = 3
 
