SELECT 
DISTINCT
GFILIAL.NOMEFANTASIA AS 'UNIDADE',
SHA.RA,
PPESSOA.NOME,
CONVERT(VARCHAR,(SELECT MIN(SHABILITACAOALUNO.RECCREATEDON) FROM SHABILITACAOALUNO WHERE SHA.RA = SHABILITACAOALUNO.RA  AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHA.IDHABILITACAOFILIAL),103) AS 'DATA INGRESSO',
CONVERT(VARCHAR,SHABILITACAOALUNOCOMPL.DATAINICIAL,103) AS 'DATA DE INICIO DO CURSO',
CONVERT(VARCHAR,SHABILITACAOALUNOCOMPL.DATAFINAL,103) AS 'DATA TERMINO PREVISTO',
(SELECT MAX(CODTURMA) FROM SMATRICPL SMP WHERE SMP.PERIODO = 1 AND SMP.RA = SHA.RA AND SMP.IDPERLET = SMP.IDPERLET AND SHA.IDHABILITACAOFILIAL = SMP.IDHABILITACAOFILIAL AND SMP.CODTURMA NOT LIKE '%PEAD%' AND SMP.CODTURMA NOT LIKE '%RT%') AS 'MODULO I',
(SELECT MAX(CODTURMA) FROM SMATRICPL SMP WHERE SMP.PERIODO = 2 AND SMP.RA = SHA.RA AND SMP.IDPERLET = SMP.IDPERLET AND SHA.IDHABILITACAOFILIAL = SMP.IDHABILITACAOFILIAL AND SMP.CODTURMA NOT LIKE '%PEAD%' AND SMP.CODTURMA NOT LIKE '%RT%') AS 'MODULO II',
(SELECT MAX(CODTURMA) FROM SMATRICPL SMP WHERE SMP.PERIODO = 3 AND SMP.RA = SHA.RA AND SMP.IDPERLET = SMP.IDPERLET AND SHA.IDHABILITACAOFILIAL = SMP.IDHABILITACAOFILIAL AND SMP.CODTURMA NOT LIKE '%PEAD%' AND SMP.CODTURMA NOT LIKE '%RT%') AS 'MODULO III',
(SELECT MAX(CODTURMA) FROM SMATRICPL SMP WHERE SMP.PERIODO = 4 AND SMP.RA = SHA.RA AND SMP.IDPERLET = SMP.IDPERLET AND SHA.IDHABILITACAOFILIAL = SMP.IDHABILITACAOFILIAL AND SMP.CODTURMA NOT LIKE '%PEAD%' AND SMP.CODTURMA NOT LIKE '%RT%') AS 'MODULO IV',
SSTATUS.DESCRICAO AS 'SITUACAO NO CURSO'

FROM SHABILITACAOALUNO SHA

INNER JOIN SHABILITACAOALUNOCOMPL ON SHABILITACAOALUNOCOMPL.CODCOLIGADA = SHA.CODCOLIGADA AND SHABILITACAOALUNOCOMPL.IDHABILITACAOFILIAL = SHA.IDHABILITACAOFILIAL AND SHABILITACAOALUNOCOMPL.RA = SHA.RA
INNER JOIN SMATRICPL ON	SHA.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SHA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL AND SHA.RA = SMATRICPL.RA
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = SHA.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHA.IDHABILITACAOFILIAL
INNER JOIN SGRADE ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
INNER JOIN SHABILITACAO ON SHABILITACAO.CODCOLIGADA = SGRADE.CODCOLIGADA AND SHABILITACAO.CODCURSO = SGRADE.CODCURSO AND SHABILITACAO.CODHABILITACAO = SGRADE.CODHABILITACAO
INNER JOIN SCURSO ON SCURSO.CODCOLIGADA = SHABILITACAO.CODCOLIGADA AND SCURSO.CODCURSO = SHABILITACAO.CODCURSO
INNER JOIN SMODALIDADECURSO ON SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO
INNER JOIN SSTATUS ON SSTATUS.CODCOLIGADA = SHA.CODCOLIGADA AND SSTATUS.CODSTATUS = SHA.CODSTATUS
INNER JOIN SALUNO ON SALUNO.CODCOLIGADA = SHA.CODCOLIGADA AND SALUNO.RA = SHA.RA
INNER JOIN PPESSOA ON PPESSOA.CODIGO = SALUNO.CODPESSOA
INNER JOIN STURMA ON STURMA.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND STURMA.CODFILIAL = SMATRICPL.CODFILIAL AND STURMA.CODTURMA = SMATRICPL.CODTURMA AND STURMA.IDPERLET = SMATRICPL.IDPERLET
INNER JOIN GFILIAL ON SMATRICPL.CODCOLIGADA = GFILIAL.CODCOLIGADA AND GFILIAL.CODFILIAL = SMATRICPL.CODFILIAL
--INNER JOIN SHABILITACAOFILIAL.CODCOLIGADA = STURMA.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = S
WHERE SHA.CODCOLIGADA = 3
--AND STURMA.CODTURMA = 'HTE-RCP-3-V2'
--AND SMATRICPL.RA  IN ('0026374','0033331','0033332','0033467','0033505','0033563','0033580','0033582','0033586','0033593','0033630','0033633','0033686','0033745','0033796','0033803','0034156','0034375','0035458','0035622','0035659')
--AND SMATRICPL.CODFILIAL = 3
AND SMODALIDADECURSO.CODMODALIDADECURSO IN ('15','31')
--SELECT * FROM SMATRICPL WHERE RA = '0001054'
--SELECT * FROM SHABILITACAOALUNO WHERE RA = '0001054'