DECLARE @DATADE  DATETIME
DECLARE @DATAATE DATETIME

SET @DATADE = '2018-01-07'
SET @DATAATE = '2018-31-07'

SELECT 


DISTINCT
RIGHT(CONVERT(VARCHAR(10),@DATADE,103),7) AS 'Referencia',
GFILIAL.NOMEFANTASIA AS 'Unidade',
SMODALIDADECURSO.DESCRICAO AS 'Modalidade',
STURNO.NOME AS 'Turno',
SCURSO.NOME AS 'Curso',
SGRADE.CARGAHORARIA AS 'CH',
ST.CODTURMA,
CONVERT(VARCHAR(10),ST.DTINICIAL,103) AS 'DataInicial',
CONVERT(VARCHAR(10),ST.DTFINAL,103) AS 'DataFinal',
(SELECT COUNT(SMATRICPL.RA) FROM STURMA

INNER JOIN SMATRICPL ON 
SMATRICPL.CODCOLIGADA  			= STURMA.CODCOLIGADA 	AND
SMATRICPL.CODFILIAL    			= STURMA.CODFILIAL 		AND
SMATRICPL.CODTURMA 				= STURMA.CODTURMA 		AND
SMATRICPL.IDPERLET 				= STURMA.IDPERLET 		AND
SMATRICPL.IDHABILITACAOFILIAL 	= STURMA.IDHABILITACAOFILIAL

WHERE SMATRICPL.CODTURMA = ST.CODTURMA


AND STURMA.CODCOLIGADA = ST.CODCOLIGADA
AND STURMA.CODFILIAL = ST.CODFILIAL
AND STURMA.IDPERLET = ST.IDPERLET
AND STURMA.IDHABILITACAOFILIAL = ST.IDHABILITACAOFILIAL
AND SMATRICPL.CODSTATUS != 1) AS 'Vagas Atendidas',

(SELECT COUNT(SMATRICPL.RA) FROM STURMA

INNER JOIN SMATRICPL ON 
SMATRICPL.CODCOLIGADA  			= STURMA.CODCOLIGADA 	AND
SMATRICPL.CODFILIAL    			= STURMA.CODFILIAL 		AND
SMATRICPL.CODTURMA 				= STURMA.CODTURMA 		AND
SMATRICPL.IDPERLET 				= STURMA.IDPERLET 		AND
SMATRICPL.IDHABILITACAOFILIAL 	= STURMA.IDHABILITACAOFILIAL

WHERE SMATRICPL.CODTURMA = ST.CODTURMA


AND STURMA.CODCOLIGADA = ST.CODCOLIGADA
AND STURMA.CODFILIAL = ST.CODFILIAL
AND STURMA.IDPERLET = ST.IDPERLET
AND STURMA.IDHABILITACAOFILIAL = ST.IDHABILITACAOFILIAL
AND SMATRICPL.CODSTATUS = 2) AS 'Matriculados'

FROM STURMA ST

INNER JOIN STURMACOMPL (NOLOCK) ON 
STURMACOMPL.CODCOLIGADA = ST.CODCOLIGADA AND
STURMACOMPL.CODFILIAL 	= ST.CODFILIAL   AND
STURMACOMPL.CODTURMA 	= ST.CODTURMA    AND
STURMACOMPL.IDPERLET 	= ST.IDPERLET
  
INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
SHABILITACAOFILIAL.CODCOLIGADA 			= ST.CODCOLIGADA 		AND
SHABILITACAOFILIAL.IDHABILITACAOFILIAL = ST.IDHABILITACAOFILIAL

INNER JOIN STURNO (NOLOCK) ON
STURNO.CODCOLIGADA 	= SHABILITACAOFILIAL.CODCOLIGADA AND
STURNO.CODTURNO 	= SHABILITACAOFILIAL.CODTURNO  

INNER JOIN SGRADE (NOLOCK) ON
SGRADE.CODCOLIGADA		= SHABILITACAOFILIAL.CODCOLIGADA 	AND
SGRADE.CODCURSO 		= SHABILITACAOFILIAL.CODCURSO 		AND
SGRADE.CODHABILITACAO 	= SHABILITACAOFILIAL.CODHABILITACAO AND
SGRADE.CODGRADE 		= SHABILITACAOFILIAL.CODGRADE
    
INNER JOIN SHABILITACAO (NOLOCK) ON
SHABILITACAO.CODCOLIGADA 	= SGRADE.CODCOLIGADA 	AND
SHABILITACAO.CODCURSO 		= SGRADE.CODCURSO 		AND
SHABILITACAO.CODHABILITACAO = SGRADE.CODHABILITACAO
   
INNER JOIN SCURSO (NOLOCK) ON
SCURSO.CODCOLIGADA 	= SHABILITACAO.CODCOLIGADA AND
SCURSO.CODCURSO 	= SHABILITACAO.CODCURSO

INNER JOIN SMODALIDADECURSO (NOLOCK) ON 
SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA AND
SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO

INNER JOIN GFILIAL (NOLOCK) ON 
ST.CODCOLIGADA 	= GFILIAL.CODCOLIGADA AND
ST.CODFILIAL 	= GFILIAL.CODFILIAL

INNER JOIN STURMADISC STD (NOLOCK) ON 

STD.CODCOLIGADA = ST.CODCOLIGADA AND 
STD.CODFILIAL = ST.CODFILIAL AND 
STD.CODTURMA = ST.CODTURMA AND
STD.IDPERLET = ST.IDPERLET


WHERE 

ST.CODCOLIGADA = 3
AND ST.DTFINAL BETWEEN @DATADE AND @DATAATE
AND SCURSO.CODMODALIDADECURSO != 0000