DECLARE @DATADE  DATETIME
DECLARE @DATAATE DATETIME

SET @DATADE = '2018-01-01'
SET @DATAATE = '2018-31-01'

SELECT * FROM (
SELECT 
	DISTINCT
	ISNULL(SI_CURSOS.CODCURSO,ISNULL(SICURSOS.CODCURSO,ISNULL(SGRADECOMPL.CURSOSCOP, ISNULL(SGRADECOMPL.IDSOLUCAOINTEGRADORA,SGRADE.CODGRADE)))) CODCURSO,
	ISNULL(SI_CURSOS.NOME_CURSO,ISNULL(SICURSOS.NOME_CURSO,ISNULL(SCURSO.COMPLEMENTO,SCURSO.NOME))) NOME_CURSO,
	ISNULL(SI_CURSOS.LINHA_ACAO,ISNULL(SICURSOS.LINHA_ACAO,SCURSOCOMPL.LINHAACAO)) LINHA_ACAO,
	ISNULL(SI_CURSOS.MODALIDADE,ISNULL(SICURSOS.MODALIDADE,SCURSO.CODMODALIDADECURSO)) MODALIDADE,
	ISNULL(SI_CURSOS.AREA,ISNULL(SICURSOS.AREA,SCURSO.CODAREA)) AREA,
	ISNULL(SI_CURSOS.EIXO,ISNULL(SICURSOS.EIXO,ISNULL(SCURSO.IDEIXOTECNOLOGICO,0))) EIXO,
	ISNULL(SI_CURSOS.CURSO_MEC,ISNULL(SICURSOS.CURSO_MEC,SCURSOCOMPL.CURSOMEC)) CURSO_MEC,
	ISNULL(SI_CURSOS.NIVEL_MEC,ISNULL(SICURSOS.NIVEL_MEC,SCURSOCOMPL.NIVELMEC)) NIVEL_MEC,
	ISNULL(SI_CURSOS.CBO,ISNULL(SICURSOS.CBO,SUBSTRING(ISNULL(SCURSOCOMPL.OCUPACAO,0),0,7))) CBO,
	ISNULL(SI_CURSOS.CHESCOLAR,ISNULL(SICURSOS.CHESCOLAR,SGRADECOMPL.CHESCOLAR)) CHESCOLAR,
	ISNULL(SI_CURSOS.CHESTAGIO,ISNULL(SICURSOS.CHESTAGIO,SGRADECOMPL.CHESTAGIO)) CHESTAGIO,
	ISNULL(SI_CURSOS.DTINICIO,ISNULL(SICURSOS.DTINICIO,CONVERT(VARCHAR(10),SGRADE.DTINICIO,103))) DTINICIO,
	CASE 
		WHEN (SI_CURSOS.DTFIM IS NOT NULL AND SI_CURSOS.DTFIM != '')  THEN SI_CURSOS.DTFIM
		WHEN (SICURSOS.DTFIM IS NOT NULL AND SICURSOS.DTFIM != '')  THEN SICURSOS.DTFIM
		WHEN (SGRADE.DTFIM IS NOT NULL AND SGRADE.DTFIM != '') AND SGRADE.DTFIM < @DATADE THEN NULL
		ELSE CONVERT(VARCHAR(10),SGRADE.DTFIM,103) 
	END DTFIM,
	0 C1,
	0 C2,
	0 C3,
	0 C4,
	0 C5,
	0 C6 
FROM   
	STURMA (NOLOCK)
	
	JOIN STURMACOMPL (NOLOCK) 
		ON STURMACOMPL.CODCOLIGADA = STURMA.CODCOLIGADA 
		AND STURMACOMPL.CODFILIAL = STURMA.CODFILIAL 
		AND STURMACOMPL.CODTURMA = STURMA.CODTURMA 
		AND STURMACOMPL.IDPERLET = STURMA.IDPERLET
		
	JOIN SHABILITACAOFILIAL (NOLOCK) 
		ON SHABILITACAOFILIAL.CODCOLIGADA = STURMA.CODCOLIGADA 
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMA.IDHABILITACAOFILIAL
	
	JOIN SCURSO (NOLOCK) 
		ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
		AND SCURSO.CODCURSO=SHABILITACAOFILIAL.CODCURSO
	
	JOIN SGRADE (NOLOCK) 
		ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
		AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO 
		AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO 
		AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
	
	JOIN SHABILITACAO (NOLOCK) 
		ON SHABILITACAO.CODCOLIGADA = SCURSO.CODCOLIGADA 
		AND SHABILITACAO.CODCURSO = SCURSO.CODCURSO
	
	JOIN SGRADECOMPL (NOLOCK) 
		ON SGRADECOMPL.CODCOLIGADA = SGRADE.CODCOLIGADA 
		AND SGRADECOMPL.CODCURSO = SGRADE.CODCURSO 
		AND SGRADECOMPL.CODHABILITACAO = SGRADE.CODHABILITACAO 
		AND SGRADECOMPL.CODGRADE = SGRADE.CODGRADE
	
	JOIN SCURSOCOMPL(NOLOCK) 
		ON SCURSO.CODCOLIGADA = SCURSOCOMPL.CODCOLIGADA 
		AND SCURSO.CODCURSO = SCURSOCOMPL.CODCURSO
	
	JOIN SHABILITACAOALUNO (NOLOCK) 
		ON SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA 
		AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
		
	JOIN SHABILITACAOALUNOCOMPL (NOLOCK)
		ON SHABILITACAOALUNOCOMPL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
		AND SHABILITACAOALUNOCOMPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
		AND SHABILITACAOALUNOCOMPL.RA = SHABILITACAOALUNO.RA
		
	JOIN SSTATUS (NOLOCK) 
		ON SSTATUS.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
		AND SSTATUS.CODSTATUS = SHABILITACAOALUNO.CODSTATUS
	
	JOIN SMATRICPL (NOLOCK) 
		ON SMATRICPL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
		AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
		AND SMATRICPL.RA = SHABILITACAOALUNO.RA 
		AND SMATRICPL.CODTURMA = STURMA.CODTURMA
		AND SMATRICPL.IDPERLET = STURMA.IDPERLET
	
	JOIN SMATRICPLCOMPL (NOLOCK) 
		ON SMATRICPLCOMPL.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
		AND SMATRICPLCOMPL.IDPERLET = SMATRICPL.IDPERLET 
		AND SMATRICPLCOMPL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL 
		AND SMATRICPLCOMPL.RA = SMATRICPL.RA
	
	LEFT JOIN SI_CURSOS (NOLOCK) 
		ON SHABILITACAOALUNOCOMPL.CODCURSO = SI_CURSOS.CODCURSO
		
	LEFT JOIN SI_CURSOS SICURSOS (NOLOCK)
		ON SGRADECOMPL.CURSOSCOP = SICURSOS.CODCURSO
		
	LEFT JOIN SLOGPLETIVO SLOGGERAL (NOLOCK)
		ON SLOGGERAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
		AND SLOGGERAL.IDPERLET = SMATRICPL.IDPERLET 
		AND SLOGGERAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL 
		AND SLOGGERAL.CODTURMA = SMATRICPL.CODTURMA 
		AND SLOGGERAL.RA = SMATRICPL.RA 
		AND SLOGGERAL.CODSTATUS = SMATRICPL.CODSTATUS
		AND SLOGGERAL.OPERACAO <> 'I'
		AND SLOGGERAL.DTALTERACAO = (SELECT 
											MAX( ULTIMAALTERACAO.DTALTERACAO)
										FROM 
											SLOGPLETIVO ULTIMAALTERACAO
                                         WHERE  
	                                         ULTIMAALTERACAO.CODCOLIGADA = SLOGGERAL.CODCOLIGADA
	                                         AND ULTIMAALTERACAO.CODFILIAL = SLOGGERAL.CODFILIAL 
	                                         AND ULTIMAALTERACAO.IDPERLET = SLOGGERAL.IDPERLET 
	                                         AND ULTIMAALTERACAO.IDHABILITACAOFILIAL = SLOGGERAL.IDHABILITACAOFILIAL 
	                                         AND ULTIMAALTERACAO.RA = SLOGGERAL.RA 
	                                         AND ULTIMAALTERACAO.CODTURMA = SLOGGERAL.CODTURMA 
	                                         AND ULTIMAALTERACAO.CODSTATUS = SLOGGERAL.CODSTATUS 
	                                         AND ULTIMAALTERACAO.OPERACAO = SLOGGERAL.OPERACAO
                                       )
    
    LEFT JOIN SLOGPLETIVO SLOGPERIODO (NOLOCK)
		ON SLOGPERIODO.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
		AND SLOGPERIODO.IDPERLET = SMATRICPL.IDPERLET 
		AND SLOGPERIODO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL 
		AND SLOGPERIODO.CODTURMA = SMATRICPL.CODTURMA 
		AND SLOGPERIODO.RA = SMATRICPL.RA 
		AND SLOGPERIODO.CODSTATUS = SMATRICPL.CODSTATUS
		AND SLOGPERIODO.OPERACAO <> 'I'
		AND SLOGPERIODO.DTALTERACAO = (SELECT 
											MAX( ULTIMAALTERACAO.DTALTERACAO)
										FROM 
											SLOGPLETIVO ULTIMAALTERACAO
                                         WHERE  
	                                         ULTIMAALTERACAO.CODCOLIGADA = SLOGPERIODO.CODCOLIGADA
	                                         AND ULTIMAALTERACAO.CODFILIAL = SLOGPERIODO.CODFILIAL 
	                                         AND ULTIMAALTERACAO.IDPERLET = SLOGPERIODO.IDPERLET 
	                                         AND ULTIMAALTERACAO.IDHABILITACAOFILIAL = SLOGPERIODO.IDHABILITACAOFILIAL 
	                                         AND ULTIMAALTERACAO.RA = SLOGPERIODO.RA 
	                                         AND ULTIMAALTERACAO.CODTURMA = SLOGPERIODO.CODTURMA 
	                                         AND ULTIMAALTERACAO.CODSTATUS = SLOGPERIODO.CODSTATUS 
	                                         AND ULTIMAALTERACAO.OPERACAO = SLOGPERIODO.OPERACAO
	                                         AND SLOGPERIODO.DTALTERACAO BETWEEN @DATADE AND @DATAATE
                                       )
		
WHERE  
	SCURSO.CODCOLIGADA = 3  
	AND STURMA.DTFINAL >= @DATADE AND STURMA.DTINICIAL <= @DATAATE 
	AND ((CONVERT(DATE,SMATRICPL.DTMATRICULA) < @DATADE) OR (CONVERT(DATE,SMATRICPL.DTMATRICULA) >= @DATADE AND CONVERT(DATE,SMATRICPL.DTMATRICULA) <= @DATAATE))
	--AND (SMATRICPLCOMPL.ENVIAPROD IS NULL OR SMATRICPLCOMPL.ENVIAPROD != 2)
	AND SMATRICPL.CODSTATUS != 1
	
	) TAB
	