----Last Day of Previous Month
SELECT DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE()),0))


----Last Day of Current Month
SELECT DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE())+1,0))


----Last Day of Next Month
SELECT DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE())+2,0))

--Last Day of Any Month and Year

SELECT DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,'2018-01-04')+1,0))

DECLARE @DT DATETIME
DECLARE @DTF DATETIME

SET @DT = CONVERT(DATETIME,'01/'+'04/2018')
SET @DTF = DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,'2018-01-04')+1,0))
SELECT @DT AS 'DATA INICIO', @DTF AS 'DATA FIM'