SELECT  DISTINCT
SAREA.NOME AS 'AREA TECNOLOGICA',
SMODALIDADECURSO.DESCRICAO AS 'MODALIDADE',
SC.NOME AS 'NOME DO CURSO',
SDISCIPLINA.NOME AS 'UNIDADE CURRICULAR'

FROM

SCURSO SC

INNER JOIN SMODALIDADECURSO ON
SMODALIDADECURSO.CODCOLIGADA = SC.CODCOLIGADA 
AND SMODALIDADECURSO.CODMODALIDADECURSO = SC.CODMODALIDADECURSO

INNER JOIN SAREA ON 
SAREA.CODCOLIGADA = SC.CODCOLIGADA 
AND SAREA.CODAREA = SC.CODAREA


INNER JOIN SHABILITACAO 
ON SHABILITACAO.CODCOLIGADA = SC.CODCOLIGADA 
AND SHABILITACAO.CODCURSO = SC.CODCURSO

INNER JOIN SGRADE ON SGRADE.CODCOLIGADA = SHABILITACAO.CODCOLIGADA 
AND SGRADE.CODCURSO = SHABILITACAO.CODCURSO 
AND SGRADE.CODHABILITACAO = SHABILITACAO.CODHABILITACAO

INNER JOIN SPERIODO ON SPERIODO.CODCOLIGADA = SGRADE.CODCOLIGADA 
AND SPERIODO.CODCURSO = SGRADE.CODCURSO 
AND SPERIODO.CODHABILITACAO = SGRADE.CODHABILITACAO 
AND SPERIODO.CODGRADE = SGRADE.CODGRADE

INNER JOIN SDISCGRADE 
ON SDISCGRADE.CODCOLIGADA = SPERIODO.CODCOLIGADA 
AND SDISCGRADE.CODCURSO = SPERIODO.CODCURSO 
AND SDISCGRADE.CODHABILITACAO = SPERIODO.CODHABILITACAO 
AND SDISCGRADE.CODGRADE = SPERIODO.CODGRADE 
AND SDISCGRADE.CODPERIODO = SPERIODO.CODPERIODO

INNER JOIN SDISCIPLINA ON 
SDISCIPLINA.CODCOLIGADA = SDISCGRADE.CODCOLIGADA 
AND SDISCIPLINA.CODDISC = SDISCGRADE.CODDISC

WHERE SC.CODCOLIGADA = 3
AND (SGRADE.STATUS != 1 OR SGRADE.STATUS IS NULL)