DECLARE @DATADE  DATETIME
DECLARE @DATAATE DATETIME

SET @DATADE = '2018-01-05'
SET @DATAATE = '2018-31-05'

SELECT 
	GFILIAL.NOMEFANTASIA AS 'Unidade_Operacional',
	SMODALIDADECURSO.DESCRICAO AS 'Modalidade',
	SCURSO.NOME AS 'Curso',
	STURMA.CODTURMA AS 'CODTURMA',
	SALUNO.RA,
	CONVERT(VARCHAR(10),SHABILITACAOALUNOCOMPL.DATAINICIAL,103) AS 'DT_Entrada',
	CONVERT(VARCHAR(10),STURMA.DTINICIAL,103) AS 'DT_Inicio_Turma',
	CONVERT(VARCHAR(10),SHABILITACAOALUNOCOMPL.DATAFINAL,103) AS 'DT_Saída_Prevista',
	CONVERT(VARCHAR(10),STURMA.DTFINAL,103) AS 'DT_Final_Turma',
	CASE WHEN LEN(FCFO.CGCCFO) <= 14 THEN ''
		ELSE
		CASE WHEN SCURSO.CODMODALIDADECURSO IN ('11','15','31','33') AND SHABILITACAOALUNOCOMPL.CONDALUNO = '1' THEN FCFO.CGCCFO
		     ELSE '' END
	END AS 'Empresa_Atendida',
	
	CASE WHEN SHABILITACAOALUNOCOMPL.CONDALUNO = '1' THEN 'Contratado'
		 WHEN SHABILITACAOALUNOCOMPL.CONDALUNO = '2' THEN 'Não Contratado'
		 WHEN SHABILITACAOALUNOCOMPL.CONDALUNO = '3' THEN 'Não se aplica'
	END AS 'CondicaoAluno',
	
	CASE WHEN SHABILITACAOALUNOCOMPL.ARTICULACAO = '1' THEN 'Sim' ELSE 'Não' END AS 'Articulacao',
	TIPOGRAT.DESCRICAO AS 'TipoGratuidade',
	INDICADOR.DESCRICAO AS  'IndicadorPronatec',

	PPESSOA.SEXO,
	PPESSOA.CORRACA,
	CASE 
	
		WHEN  PPESSOA.GRAUINSTRUCAO IS NULL THEN 'Não preenchido'
		ELSE PPESSOA.GRAUINSTRUCAO
	END AS 'Escolaridade'
	
FROM SMATRICPL
	SMATRICPL (NOLOCK)
	
JOIN SHABILITACAOALUNO (NOLOCK)
ON   SHABILITACAOALUNO.CODCOLIGADA 			= SMATRICPL.CODCOLIGADA 
AND  SHABILITACAOALUNO.IDHABILITACAOFILIAL 	= SMATRICPL.IDHABILITACAOFILIAL 
AND  SHABILITACAOALUNO.RA 					= SMATRICPL.RA

JOIN SHABILITACAOALUNOCOMPL (NOLOCK) 
ON   SHABILITACAOALUNOCOMPL.CODCOLIGADA 		= SHABILITACAOALUNO.CODCOLIGADA 
AND  SHABILITACAOALUNOCOMPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
AND  SHABILITACAOALUNOCOMPL.RA 					= SHABILITACAOALUNO.RA

JOIN SMATRICPLCOMPL (NOLOCK) 
ON   SMATRICPLCOMPL.CODCOLIGADA 		= SMATRICPL.CODCOLIGADA 
AND  SMATRICPLCOMPL.IDPERLET 			= SMATRICPL.IDPERLET 
AND  SMATRICPLCOMPL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL 
AND  SMATRICPLCOMPL.RA 					= SMATRICPL.RA

JOIN SALUNO (NOLOCK) 
ON   SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
AND  SALUNO.RA 			= SHABILITACAOALUNO.RA

JOIN SALUNOCOMPL (NOLOCK) 
ON SALUNOCOMPL.CODCOLIGADA = SALUNO.CODCOLIGADA 
AND SALUNOCOMPL.RA = SALUNO.RA

LEFT JOIN SCONTRATO 
ON  SCONTRATO.CODCOLIGADA 			= SMATRICPL.CODCOLIGADA 
AND SCONTRATO.IDPERLET 				= SMATRICPL.IDPERLET 
AND SCONTRATO.IDHABILITACAOFILIAL 	= SMATRICPL.IDHABILITACAOFILIAL 
AND SCONTRATO.RA 					= SMATRICPL.RA
AND SCONTRATO.CODCONTRATO 			= (SELECT MAX(CODCONTRATO) FROM SCONTRATO SC(NOLOCK)
										WHERE SMATRICPL.CODCOLIGADA   		 	= SC.CODCOLIGADA
										AND   SMATRICPL.RA     	   		 		= SC.RA
										AND	  SMATRICPL.IDHABILITACAOFILIAL 	= SC.IDHABILITACAOFILIAL
										AND   SMATRICPL.IDPERLET 			 	= SC.IDPERLET)
								
LEFT JOIN SRESPONSAVELCONTRATO (NOLOCK)
ON  SRESPONSAVELCONTRATO.CODCOLIGADA 	= SCONTRATO.CODCOLIGADA 
AND SRESPONSAVELCONTRATO.RA 			= SCONTRATO.RA 
AND SRESPONSAVELCONTRATO.CODCONTRATO 	= SCONTRATO.CODCONTRATO 
AND SRESPONSAVELCONTRATO.IDPERLET 		= SCONTRATO.IDPERLET

LEFT JOIN GFILIAL (NOLOCK)
ON  GFILIAL.CODCOLIGADA	= SMATRICPL.CODCOLIGADA 
AND GFILIAL.CODFILIAL	= SMATRICPL.CODFILIAL

LEFT JOIN FCFO  (NOLOCK)
ON  FCFO.CODCOLIGADA = SRESPONSAVELCONTRATO.CODCOLCFO	
AND FCFO.CODCFO 		= SRESPONSAVELCONTRATO.CODCFO

JOIN PPESSOA (NOLOCK) 
ON   PPESSOA.CODIGO = SALUNO.CODPESSOA

JOIN STURMA (NOLOCK) 
ON   STURMA.CODCOLIGADA  = SMATRICPL.CODCOLIGADA 
AND  STURMA.CODFILIAL 	 = SMATRICPL.CODFILIAL 
AND  STURMA.CODTURMA 	 = SMATRICPL.CODTURMA 
AND  STURMA.IDPERLET 	 = SMATRICPL.IDPERLET

JOIN STURMACOMPL (NOLOCK) 
ON   STURMACOMPL.CODCOLIGADA 	= STURMA.CODCOLIGADA 
AND  STURMACOMPL.CODFILIAL 		= STURMA.CODFILIAL 
AND  STURMACOMPL.CODTURMA 		= STURMA.CODTURMA 
AND  STURMACOMPL.IDPERLET 		= STURMA.IDPERLET

LEFT JOIN GCONSIST TIPOGRAT(NOLOCK)
ON  SHABILITACAOALUNOCOMPL.TIPOGRAT = TIPOGRAT.CODINTERNO 
AND TIPOGRAT.CODTABELA 				= 'TIPOGRAT'

LEFT JOIN GCONSIST INDICADOR(NOLOCK) 
ON   SHABILITACAOALUNOCOMPL.PRONATEC 	= INDICADOR.CODINTERNO 
AND  INDICADOR.CODTABELA 				= 'INDICADOR'

JOIN SHABILITACAOFILIAL (NOLOCK) 
ON   SHABILITACAOFILIAL.CODCOLIGADA 		= SHABILITACAOALUNO.CODCOLIGADA 
AND  SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL

JOIN SGRADE (NOLOCK) 
ON   SGRADE.CODCOLIGADA 	= SHABILITACAOFILIAL.CODCOLIGADA 
AND  SGRADE.CODCURSO 		= SHABILITACAOFILIAL.CODCURSO 
AND  SGRADE.CODHABILITACAO 	= SHABILITACAOFILIAL.CODHABILITACAO 
AND  SGRADE.CODGRADE 		= SHABILITACAOFILIAL.CODGRADE


JOIN SHABILITACAO (NOLOCK)
ON   SHABILITACAO.CODCOLIGADA = SGRADE.CODCOLIGADA 
AND  SHABILITACAO.CODCURSO = SGRADE.CODCURSO 
AND  SHABILITACAO.CODHABILITACAO = SGRADE.CODHABILITACAO

JOIN SCURSO (NOLOCK) 
ON 	 SCURSO.CODCOLIGADA = SHABILITACAO.CODCOLIGADA 
AND  SCURSO.CODCURSO 	= SHABILITACAO.CODCURSO

JOIN SMODALIDADECURSO 
ON   SMODALIDADECURSO.CODCOLIGADA 		 = SCURSO.CODCOLIGADA 
AND  SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO


WHERE SMATRICPL.CODCOLIGADA = 3
	AND  STURMA.DTINICIAL BETWEEN @DATADE AND @DATAATE
	AND (SMATRICPLCOMPL.ENVIAPROD IS NULL OR SMATRICPLCOMPL.ENVIAPROD != 2)
	--AND ((CONVERT(DATE,SLOGPLETIVO.DTALTERACAO) >= @DATADE)OR (SMATRICPL.CODSTATUS = '2'))
	AND STURMACOMPL.TIPOTURMA NOT IN ('11','12')
	AND SMATRICPL.CODSTATUS    != 1
	AND((CONVERT(DATE,SHABILITACAOALUNOCOMPL.DATAINICIAL)!= CONVERT(DATE,STURMA.DTINICIAL) AND SCURSO.CODMODALIDADECURSO NOT IN ('31','15')) 
		OR(CONVERT(DATE,SHABILITACAOALUNOCOMPL.DATAFINAL)!= CONVERT(DATE,STURMA.DTFINAL) AND SCURSO.CODMODALIDADECURSO NOT IN ('31','15')) 
		OR(SHABILITACAOALUNOCOMPL.CONDALUNO = '1' AND SCURSO.CODMODALIDADECURSO NOT IN ('11','15'))
		OR(SHABILITACAOALUNOCOMPL.ARTICULACAO = '1' AND SCURSO.CODMODALIDADECURSO != '31')
		OR(PPESSOA.GRAUINSTRUCAO IS NULL)
		OR(PPESSOA.CORRACA IS NULL))