SELECT DISTINCT
	SMATRICULA.RA,
	SCURSO.NOME AS CURSO,
   	SDISCIPLINA.NOME AS DISCIPLINA,
	SDISCIPLINA.CH,
	FALTA.NOTAFALTA AS FALTA,
	PERC.NOTAFALTA AS PERC,
	NOTA.NOTAFALTA AS NOTA,
	SPERIODO.DESCRICAO AS PERIODO,
	PPESSOA.NOME AS ALUNO,
	ISNULL(STATUSFINAL.DESCRICAO,ISNULL(STATUSMATRICULA.DESCRICAO,'')) SITUACAO,
	SDISCGRADE.POSHIST

FROM
	SMATRICULA (NOLOCK)
	
	INNER JOIN SNOTAETAPA FALTA ON 
		FALTA.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
		FALTA.IDTURMADISC = SMATRICULA.IDTURMADISC AND 
		FALTA.RA = SMATRICULA.RA AND
		FALTA.CODETAPA = 30 AND
		FALTA.TIPOETAPA = 'F'
		
   	INNER JOIN SNOTAETAPA PERC ON 
		PERC.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
		PERC.IDTURMADISC = SMATRICULA.IDTURMADISC AND 
		PERC.RA = SMATRICULA.RA AND
		PERC.CODETAPA IN(31,61) AND
		PERC.TIPOETAPA = 'F'
		
	INNER JOIN SNOTAETAPA NOTA ON 
		NOTA.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
		NOTA.IDTURMADISC = SMATRICULA.IDTURMADISC AND 
		NOTA.RA = SMATRICULA.RA AND
		NOTA.CODETAPA = 3 AND
		NOTA.TIPOETAPA = 'N'
	
	INNER JOIN STURMADISC ON 
		STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
		STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	
	INNER JOIN STURMA ON 
		STURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND 
		STURMA.CODFILIAL = STURMADISC.CODFILIAL AND 
		STURMA.CODTURMA = STURMADISC.CODTURMA AND 
		STURMA.IDPERLET = STURMADISC.IDPERLET
		
	INNER JOIN STURMACOMPL ON STURMACOMPL.CODCOLIGADA = STURMA.CODCOLIGADA AND 
		STURMACOMPL.CODFILIAL = STURMA.CODFILIAL AND 
		STURMACOMPL.CODTURMA = STURMA.CODTURMA AND 
		STURMACOMPL.IDPERLET = STURMA.IDPERLET
		
	INNER JOIN SMATRICPL ON 
		SMATRICPL.CODCOLIGADA = STURMA.CODCOLIGADA AND 
		SMATRICPL.CODFILIAL = STURMA.CODFILIAL AND 
		SMATRICPL.CODTURMA = STURMA.CODTURMA AND 
		SMATRICPL.IDPERLET = STURMA.IDPERLET
		
	INNER JOIN SHABILITACAOALUNO ON 
		SHABILITACAOALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND 
		SHABILITACAOALUNO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL AND 
		SHABILITACAOALUNO.RA = SMATRICPL.RA
		
	INNER JOIN SHABILITACAOFILIAL ON 
		SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA AND 
		SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL

	INNER JOIN SGRADE ON 
		SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND 
		SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO AND 
		SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO AND 
		SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
	
	INNER JOIN SDISCGRADE ON 
		SDISCGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND 
		SDISCGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO AND 
		SDISCGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO AND 
		SDISCGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE AND 
		SDISCGRADE.CODDISC = STURMADISC.CODDISC
					
   	INNER JOIN SDISCIPLINA ON 
		SDISCIPLINA.CODCOLIGADA = SDISCGRADE.CODCOLIGADA AND 
		SDISCIPLINA.CODDISC = SDISCGRADE.CODDISC
		
	INNER JOIN SPERIODO ON 
		SPERIODO.CODCOLIGADA = SDISCGRADE.CODCOLIGADA AND 
		SPERIODO.CODCURSO = SDISCGRADE.CODCURSO AND 
		SPERIODO.CODHABILITACAO = SDISCGRADE.CODHABILITACAO AND 
		SPERIODO.CODGRADE = SDISCGRADE.CODGRADE AND 
		SPERIODO.CODPERIODO = SDISCGRADE.CODPERIODO
	
	INNER JOIN SHABILITACAO ON 
	SHABILITACAO.CODCOLIGADA = SGRADE.CODCOLIGADA AND 
	SHABILITACAO.CODCURSO = SGRADE.CODCURSO AND 
	SHABILITACAO.CODHABILITACAO = SGRADE.CODHABILITACAO
	
	INNER JOIN SCURSO ON 
		SCURSO.CODCOLIGADA = SHABILITACAO.CODCOLIGADA AND 
		SCURSO.CODCURSO = SHABILITACAO.CODCURSO
		
	INNER JOIN SALUNO ON SALUNO.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND SALUNO.RA = SMATRICULA.RA
	
	INNER JOIN PPESSOA (NOLOCK)
		ON PPESSOA.CODIGO = SALUNO.CODPESSOA 
	
	LEFT JOIN SSTATUS STATUSMATRICULA(NOLOCK)
		ON  SMATRICULA.CODCOLIGADA = STATUSMATRICULA.CODCOLIGADA
		AND SMATRICULA.CODSTATUS = STATUSMATRICULA.CODSTATUS
	
	LEFT JOIN SSTATUS STATUSFINAL (NOLOCK)
		ON  SMATRICULA.CODCOLIGADA = STATUSFINAL.CODCOLIGADA
		AND SMATRICULA.CODSTATUSRES = STATUSFINAL.CODSTATUS
		
WHERE
	SMATRICULA.CODCOLIGADA = 3 AND
	STURMACOMPL.TIPOTURMA NOT IN(11,12)AND
	SMATRICPL.COFILIAL = 3 AND
	SMATRICULA.RA = 