SELECT DISTINCT
	SMATRICULA.RA,
	SCURSO.NOME AS CURSO,
   	SDISCIPLINA.NOME AS DISCIPLINA,
	SDISCIPLINA.CH,
	FALTA.NOTAFALTA AS FALTA,
	PERC.NOTAFALTA AS PERC,
	NOTA.NOTAFALTA AS NOTA,
	SMATRICULA.DTMATRICULA,
	SPERIODO.DESCRICAO AS PERIODO,
	PPESSOA.NOME AS ALUNO,
	ISNULL(STATUSFINAL.DESCRICAO,ISNULL(STATUSMATRICULA.DESCRICAO,'')) SITUACAO,
	SDISCGRADE.POSHIST

FROM
	SMATRICULA (NOLOCK)
	
	LEFT JOIN SNOTAETAPA FALTA (NOLOCK) ON 
		FALTA.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
		FALTA.IDTURMADISC = SMATRICULA.IDTURMADISC AND 
		FALTA.RA = SMATRICULA.RA AND
		FALTA.CODETAPA = 30 AND
		FALTA.TIPOETAPA = 'F'
		
   	LEFT JOIN SNOTAETAPA PERC (NOLOCK) ON 
		PERC.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
		PERC.IDTURMADISC = SMATRICULA.IDTURMADISC AND 
		PERC.RA = SMATRICULA.RA AND
		PERC.CODETAPA IN(31,61) AND
		PERC.TIPOETAPA = 'F'
		
	LEFT JOIN SNOTAETAPA NOTA (NOLOCK) ON 
		NOTA.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
		NOTA.IDTURMADISC = SMATRICULA.IDTURMADISC AND 
		NOTA.RA = SMATRICULA.RA AND
		NOTA.CODETAPA = 3 AND
		NOTA.TIPOETAPA = 'N'
	
	INNER JOIN STURMADISC (NOLOCK) ON 
		STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
		STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	
	INNER JOIN(	SELECT 
				SMATRICULA.CODCOLIGADA,
				STURMADISC.CODDISC,
				MAX(SMATRICULA.DTMATRICULA) DTMATRICULA
				
			FROM
				SMATRICULA (NOLOCK)
				
				INNER JOIN STURMADISC ON 
				STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
				STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
					
			WHERE
				SMATRICULA.CODCOLIGADA = 3
				AND	SMATRICULA.RA = '0049578'
				
			GROUP BY
				SMATRICULA.CODCOLIGADA,
				STURMADISC.CODDISC)
				SUB ON
				SUB.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND
				SUB.CODDISC = STURMADISC.CODDISC 
			   	AND	SUB.DTMATRICULA = SMATRICULA.DTMATRICULA
		
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON 
		SHABILITACAOFILIAL.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
		SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL

	INNER JOIN SGRADE (NOLOCK) ON 
		SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND 
		SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO AND 
		SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO AND 
		SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
	
	INNER JOIN SDISCGRADE (NOLOCK) ON 
		SDISCGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND 
		SDISCGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO AND 
		SDISCGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO AND 
		SDISCGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE AND 
		SDISCGRADE.CODDISC = STURMADISC.CODDISC
					
   	INNER JOIN SDISCIPLINA (NOLOCK) ON 
		SDISCIPLINA.CODCOLIGADA = SDISCGRADE.CODCOLIGADA AND 
		SDISCIPLINA.CODDISC = SDISCGRADE.CODDISC
		
	INNER JOIN SPERIODO (NOLOCK) ON 
		SPERIODO.CODCOLIGADA = SDISCGRADE.CODCOLIGADA AND 
		SPERIODO.CODCURSO = SDISCGRADE.CODCURSO AND 
		SPERIODO.CODHABILITACAO = SDISCGRADE.CODHABILITACAO AND 
		SPERIODO.CODGRADE = SDISCGRADE.CODGRADE AND 
		SPERIODO.CODPERIODO = SDISCGRADE.CODPERIODO
	
	INNER JOIN SHABILITACAO (NOLOCK) ON 
	SHABILITACAO.CODCOLIGADA = SGRADE.CODCOLIGADA AND 
	SHABILITACAO.CODCURSO = SGRADE.CODCURSO AND 
	SHABILITACAO.CODHABILITACAO = SGRADE.CODHABILITACAO
	
	INNER JOIN SCURSO (NOLOCK) ON 
		SCURSO.CODCOLIGADA = SHABILITACAO.CODCOLIGADA AND 
		SCURSO.CODCURSO = SHABILITACAO.CODCURSO
		
	INNER JOIN SALUNO (NOLOCK) ON SALUNO.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND SALUNO.RA = SMATRICULA.RA
	
	INNER JOIN PPESSOA (NOLOCK)
		ON PPESSOA.CODIGO = SALUNO.CODPESSOA 
	
	LEFT JOIN SSTATUS STATUSMATRICULA(NOLOCK)
		ON  SMATRICULA.CODCOLIGADA = STATUSMATRICULA.CODCOLIGADA
		AND SMATRICULA.CODSTATUS = STATUSMATRICULA.CODSTATUS
	
	LEFT JOIN SSTATUS STATUSFINAL (NOLOCK)
		ON  SMATRICULA.CODCOLIGADA = STATUSFINAL.CODCOLIGADA
		AND SMATRICULA.CODSTATUSRES = STATUSFINAL.CODSTATUS
		
WHERE
	SMATRICULA.CODCOLIGADA = 3 AND
	STURMADISC.CODFILIAL = 3 AND
	SMATRICULA.RA = '0049578'

ORDER BY 8,11