DECLARE @DE DATETIME
DECLARE @ATE DATETIME

SET @DE = '2018-05-03'
SET @ATE = '2018-10-03'

SELECT 
GFILIAL.NOMEFANTASIA,
SMODALIDADECURSO.DESCRICAO,
V_SI_CHDISCIPLINA.CODTURMA,
CONVERT(INT, ISNULL(SUM(V_SI_CHDISCIPLINA.HRDISC),0)) AS 'HORAS PREVISTAS'

FROM V_SI_CHDISCIPLINA

INNER JOIN STURMADISC ON V_SI_CHDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND V_SI_CHDISCIPLINA.CODFILIAL = STURMADISC.CODFILIAL AND V_SI_CHDISCIPLINA.IDPERLET = STURMADISC.IDPERLET  AND V_SI_CHDISCIPLINA.CODTURMA = STURMADISC.CODTURMA AND V_SI_CHDISCIPLINA.IDTURMADISC = STURMADISC.IDTURMADISC
INNER JOIN STURMA ON STURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND STURMA.CODFILIAL = STURMADISC.CODFILIAL AND STURMA.CODTURMA = STURMADISC.CODTURMA AND STURMA.IDPERLET = STURMADISC.IDPERLET
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = STURMA.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMA.IDHABILITACAOFILIAL
INNER JOIN SGRADE ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
INNER JOIN SHABILITACAO ON SHABILITACAO.CODCOLIGADA = SGRADE.CODCOLIGADA AND SHABILITACAO.CODCURSO = SGRADE.CODCURSO AND SHABILITACAO.CODHABILITACAO = SGRADE.CODHABILITACAO
INNER JOIN SCURSO ON SCURSO.CODCOLIGADA = SHABILITACAO.CODCOLIGADA AND SCURSO.CODCURSO = SHABILITACAO.CODCURSO
INNER JOIN SMODALIDADECURSO ON SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO
INNER JOIN GFILIAL ON STURMA.CODCOLIGADA = GFILIAL.CODCOLIGADA AND  STURMA.CODFILIAL = GFILIAL.CODFILIAL
WHERE V_SI_CHDISCIPLINA.CODCOLIGADA = 3
AND V_SI_CHDISCIPLINA.CODFILIAL = 4
AND V_SI_CHDISCIPLINA.DATA BETWEEN @DE AND @ATE
GROUP BY 
GFILIAL.NOMEFANTASIA,
SMODALIDADECURSO.DESCRICAO,
V_SI_CHDISCIPLINA.CODTURMA
ORDER BY GFILIAL.NOMEFANTASIA
