SELECT
DISTINCT
GF.NOMEFANTASIA 	AS 'UNIDADE',
--SMC.DESCRICAO		AS 'MODALIDADE',
SC.NOME 			AS 'CURSO',
--ST.CODTURMA 		AS 'TURMA',
CASE STN.TIPO
	WHEN 'I' THEN 'Integral'
	WHEN 'M' THEN 'Matutino'
	WHEN 'V' THEN 'Vespertino'
	WHEN 'N' THEN 'Noturno'
END AS 'TURNO',
ST.DTINICIAL        AS 'DATAINICIAL',
ST.DTFINAL	        AS 'DATAFINAL',
GC.DESCRICAO        AS 'TIPOTURMA',
ST.MAXALUNOS        AS 'VAGAS OFERTADAS',
	(	SELECT COUNT(SPSIAO.NUMEROINSCRICAO)
		FROM
		SPSOPCAOINSCRITO SPSOI(NOLOCK)
		INNER JOIN SPSPROCESSOSELETIVO SPSPS(NOLOCK)
		ON SPSOI.IDPS = SPSPS.IDPS
		
		INNER JOIN SPSAREAINTERESSE SPSAI(NOLOCK)
		ON SPSOI.IDAREAINTERESSE = SPSAI.IDAREAINTERESSE
		AND SPSOI.CODCOLIGADA = SPSAI.CODCOLIGADAHABFILIAL
		
		INNER JOIN SPSINSCRICAOAREAOFERTADA SPSIAO ON 
			SPSIAO.CODCOLIGADA = SPSOI.CODCOLIGADA AND 
			SPSIAO.IDPS = SPSOI.IDPS AND 
			SPSIAO.NUMEROINSCRICAO = SPSOI.NUMEROINSCRICAO
	  
		
		WHERE 
			SPSPS.STATUS = 'T' AND
			SPSPS.CODCOLIGADA = ST.CODCOLIGADA AND
			SPSPS.CODFILIAL = ST.CODFILIAL AND
			SPSAI.IDHABILITACAOFILIAL = ST.IDHABILITACAOFILIAL AND
			SPSOI.CODPESSOA NOT IN(SELECT DISTINCT CODPESSOA FROM SALUNO
									INNER JOIN SMATRICPL ON SMATRICPL.CODCOLIGADA = SALUNO.CODCOLIGADA AND SMATRICPL.RA = SALUNO.RA
									WHERE SMATRICPL.CODCOLIGADA = ST.CODCOLIGADA AND
									SMATRICPL.CODFILIAL = ST.CODFILIAL AND
									SMATRICPL.IDHABILITACAOFILIAL = SPSAI.IDHABILITACAOFILIAL
									)
			) AS 'INSCRITOS',
			
(SELECT COUNT(SMATRICPL.RA) FROM SMATRICPL
 WHERE SMATRICPL.CODCOLIGADA = ST.CODCOLIGADA
 AND   SMATRICPL.CODFILIAL   = ST.CODFILIAL
 AND   SMATRICPL.IDHABILITACAOFILIAL = ST.IDHABILITACAOFILIAL
 AND   SMATRICPL.CODTURMA = ST.CODTURMA
 AND   SMATRICPL.IDPERLET = ST.IDPERLET)
 AS 'MATRICULADOS'
 
FROM STURMA ST(NOLOCK)

INNER JOIN GFILIAL GF(NOLOCK)ON
	ST.CODCOLIGADA = GF.CODCOLIGADA
AND ST.CODFILIAL   = GF.CODFILIAL



INNER JOIN SHABILITACAOFILIAL SHF(NOLOCK)ON
	ST.CODCOLIGADA 			= SHF.CODCOLIGADA
AND ST.CODFILIAL   			= SHF.CODFILIAL
AND ST.IDHABILITACAOFILIAL	= SHF.IDHABILITACAOFILIAL

INNER JOIN STURNO STN(NOLOCK)ON
	SHF.CODCOLIGADA = STN.CODCOLIGADA
AND SHF.CODTURNO    = STN.CODTURNO
AND SHF.CODFILIAL   = STN.CODFILIAL

INNER JOIN SCURSO SC(NOLOCK)ON
	SHF.CODCOLIGADA = SC.CODCOLIGADA
AND SHF.CODCURSO 	= SC.CODCURSO

INNER JOIN SMODALIDADECURSO SMC(NOLOCK)ON
	SMC.CODCOLIGADA = SC.CODCOLIGADA
AND SMC.CODMODALIDADECURSO  = SC.CODMODALIDADECURSO

INNER JOIN STURMACOMPL STC(NOLOCK)ON
	ST.CODCOLIGADA = STC.CODCOLIGADA
AND ST.CODFILIAL   = STC.CODFILIAL
AND ST.IDPERLET    = STC.IDPERLET
AND ST.CODTURMA    = STC.CODTURMA

LEFT JOIN GCONSIST GC(NOLOCK)ON
	STC.TIPOTURMA = GC.CODINTERNO
AND GC.CODTABELA = 'TIPOTURMA'
WHERE ST.CODCOLIGADA = 3 
AND ST.DTINICIAL BETWEEN '2018-01-07' AND '2018-31-07'
AND ST.CODTURMA IN ('HTC-ATI-1-29','HTC-ATI-1-30','HTC-ELT-1-37','HTC-MEC-1-70','HTC-MEC-1-71-A','HTC-MEC-1-71-B','HTC-MECT-1-1','HTC-MECT-1-2','HTC-SGT-1-23','HTC-SGT-1-24','HTC-MEC-1-12','HTC-MEC-1-13','HTC-PLT-1-4','HTC-RFC-1-4','HTC-ALI-1-4','HTC-EDI-1-9-A','HTC-EDI-1-9-B','HTC-ELT-1-6','HTC-LOG-1-5','HTC-MOV-1-4','HTC-ELT-1-5','HTC-MEC-1-5','HTC-SGT-1-1','HTC-ELT-1-1','HTC-ELT-1-2','HTC-MEC-1-27','HTC-MEC-1-28','HTC-ELT-1-4','HTC-MEC-1-5','HTC-VES-1-3','HTC-ELT-1-2','HTC-MEC-1-3','HTC-DSI-1-4','HTC-DEST-1-3')