SELECT DISTINCT
 GF.NOMEFANTASIA 		AS 'Unidade',
 MT.RA 					AS 'RA',
 MT.ALUNO 				AS 'Aluno',
 GC1.DESCRICAO			AS 'Necessidade',
 GC2.DESCRICAO			AS 'Escola Origem',
 MT.NOMECURSO 			AS 'Curso',
 MT.DESCGRADE			AS 'Grade',
 MT.MODALIDADE 			AS 'Modalidade',
 MT.CODTURMA 			AS 'CodTurma',
 MT.NOMEDOTURNO 		AS 'Turno',
 SMP.PERIODO 			AS 'Período',
 CASE STC.TRETIDA
	 WHEN '1' THEN 'NÃO'
	 ELSE 'SIM' END		AS 'Turma Regular',
 SHAC.DATAINICIAL 		AS 'Inicio do Curso',
 SHAC.DATAFINAL			AS 'Término Previsto',
 ST.DTINICIAL 			AS 'Data Inicial',
 ST.DTFINAL 			AS 'Data Final', 
 MT.CPF					AS 'Cpf',
 CF.CGCCFO 				AS 'CNJP/CPF Responsavel',
 CF.NOMEFANTASIA		AS 'Responsavel',
 MT.STATMATRICPL 		AS 'Situação',
 SLOGPLETIVO.DTALTERACAO AS 'DT saída',
 CASE SHAC.TIPOGRAT
	 WHEN '1' THEN 'Gratuidade'
	 WHEN '2' THEN 'Bolsa de Estudos'
	 WHEN '3' THEN 'Convênio'
	 WHEN '4' THEN 'Pronatec'
	 WHEN '5' THEN 'Não Gratuita'
	 ELSE NULL END		AS 'Tipo de Gratuidade',
 GC.DESCRICAO			AS 'Indicador PRONATEC',
 CASE SHAC.CONDALUNO
	 WHEN '1' THEN 'Contratado'
	 WHEN '2' THEN 'Não Contratado'
	 WHEN '3' THEN 'Não se aplica'
	 ELSE NULL END 		AS 'Condição do Aluno',
CASE SHAC.ARTICULACAO	
	 WHEN '1' THEN 'Sim'
	 WHEN '2' THEN 'Não'
	 ELSE NULL END 		AS 'Articulação SESI-SENAI',
CASE SMPC.ENVIAPROD
	 WHEN '2' THEN 'Não'
	 ELSE 'Sim' END 	AS 'Envia Produção'
 
FROM 
 ZVWMATRICPL MT(NOLOCK)
  
INNER JOIN GFILIAL GF(NOLOCK)ON
	MT.CODCOLIGADA = GF.CODCOLIGADA
AND MT.CODFILIAL   = GF.CODFILIAL

INNER JOIN SMATRICPL SMP(NOLOCK)ON
	MT.CODCOLIGADA   		= SMP.CODCOLIGADA
AND MT.IDPERLET   			= SMP.IDPERLET
AND MT.IDHABILITACAOFILIAL 	= SMP.IDHABILITACAOFILIAL
AND MT.RA     				= SMP.RA
AND SMP.PERIODO				= (SELECT MAX(PERIODO) FROM SMATRICPL  SMP2(NOLOCK)
								WHERE SMP.RA 	  				 = SMP2.RA
								AND   SMP.CODCOLIGADA   		 = SMP2.CODCOLIGADA
								AND   SMP.CODFILIAL   			 = SMP2.CODFILIAL
								AND	  SMP.IDHABILITACAOFILIAL	 = SMP2.IDHABILITACAOFILIAL)

LEFT JOIN SLOGPLETIVO ON 
			SLOGPLETIVO.CODCOLIGADA = SMP.CODCOLIGADA 
		AND SLOGPLETIVO.IDPERLET = SMP.IDPERLET 
	    AND SLOGPLETIVO.IDHABILITACAOFILIAL = SMP.IDHABILITACAOFILIAL 
		AND SLOGPLETIVO.CODTURMA = SMP.CODTURMA 
		AND SLOGPLETIVO.RA = SMP.RA 
	    AND SLOGPLETIVO.DTALTERACAO = (SELECT MAX( ULTIMAALTERACAO.DTALTERACAO)
												FROM 
													SLOGPLETIVO ULTIMAALTERACAO
												 WHERE  
													 ULTIMAALTERACAO.CODCOLIGADA = SLOGPLETIVO.CODCOLIGADA
													 AND ULTIMAALTERACAO.CODFILIAL = SLOGPLETIVO.CODFILIAL 
													 AND ULTIMAALTERACAO.IDPERLET = SLOGPLETIVO.IDPERLET 
													 AND ULTIMAALTERACAO.IDHABILITACAOFILIAL = SLOGPLETIVO.IDHABILITACAOFILIAL 
													 AND ULTIMAALTERACAO.RA = SLOGPLETIVO.RA 
													 AND ULTIMAALTERACAO.CODTURMA = SLOGPLETIVO.CODTURMA 
													 AND ULTIMAALTERACAO.OPERACAO NOT IN ('I','E')
												
																					 
											   )
											   
INNER JOIN SMATRICPLCOMPL SMPC(NOLOCK)ON
	MT.CODCOLIGADA   		= SMPC.CODCOLIGADA
AND MT.IDPERLET   			= SMPC.IDPERLET
AND MT.IDHABILITACAOFILIAL 	= SMPC.IDHABILITACAOFILIAL
AND MT.RA     				= SMPC.RA
 
LEFT JOIN SCONTRATO(NOLOCK)ON
	MT.CODCOLIGADA   		= SCONTRATO.CODCOLIGADA
AND MT.RA     				= SCONTRATO.RA
AND MT.IDHABILITACAOFILIAL 	= SCONTRATO.IDHABILITACAOFILIAL
AND MT.IDPERLET   			= SCONTRATO.IDPERLET
AND SCONTRATO.CODCONTRATO 	= (SELECT MAX(CODCONTRATO) FROM SCONTRATO SC(NOLOCK)
								WHERE MT.CODCOLIGADA   		 = SC.CODCOLIGADA
								AND   MT.RA     	   		 = SC.RA
								AND	  MT.IDHABILITACAOFILIAL = SC.IDHABILITACAOFILIAL
								AND   MT.IDPERLET 			 = SC.IDPERLET)
								
LEFT JOIN SRESPONSAVELCONTRATO(NOLOCK)ON
	SCONTRATO.CODCOLIGADA 	= SRESPONSAVELCONTRATO.CODCOLIGADA 
AND SCONTRATO.RA 			= SRESPONSAVELCONTRATO.RA 
AND SCONTRATO.CODCONTRATO 	= SRESPONSAVELCONTRATO.CODCONTRATO 
AND SCONTRATO.IDPERLET 		= SRESPONSAVELCONTRATO.IDPERLET

LEFT JOIN FCFO CF(NOLOCK)
ON SRESPONSAVELCONTRATO.CODCFO = CF.CODCFO

INNER JOIN STURMA ST(NOLOCK)ON
	ST.CODCOLIGADA 	= MT.CODCOLIGADA
AND ST.CODTURMA 	= MT.CODTURMA
AND ST.CODFILIAL 	= MT.CODFILIAL
AND ST.IDPERLET 	= MT.IDPERLET

INNER JOIN STURMACOMPL STC(NOLOCK)ON 
	ST.CODCOLIGADA = STC.CODCOLIGADA
AND ST.CODTURMA    = STC.CODTURMA
AND ST.CODFILIAL   = STC.CODFILIAL
AND ST.IDPERLET    = STC.IDPERLET
  
INNER JOIN SHABILITACAOALUNO SHA(NOLOCK)ON
	MT.CODCOLIGADA 			= SHA.CODCOLIGADA
AND MT.IDHABILITACAOFILIAL 	= SHA.IDHABILITACAOFILIAL
AND MT.RA 					= SHA.RA
	
INNER JOIN SHABILITACAOALUNOCOMPL SHAC(NOLOCK)ON
	MT.CODCOLIGADA 			= SHAC.CODCOLIGADA
AND MT.IDHABILITACAOFILIAL 	= SHAC.IDHABILITACAOFILIAL
AND MT.RA 					= SHAC.RA

INNER JOIN SALUNOCOMPL SAC(NOLOCK)ON
	MT.RA 			= SAC.RA
AND MT.CODCOLIGADA  = SAC.CODCOLIGADA

LEFT JOIN GCONSIST GC(NOLOCK)ON
	SHAC.PRONATEC = GC.CODINTERNO
AND GC.CODTABELA = 'INDICADOR'


LEFT JOIN GCONSIST GC1(NOLOCK)ON
	SAC.NECESSIDADES = GC1.CODINTERNO
AND GC1.CODTABELA = 'NECESSIDAD'

LEFT JOIN GCONSIST GC2(NOLOCK)ON
	SAC.TIPOESCOLA = GC2.CODINTERNO
AND GC2.CODTABELA = 'TIPOESCOLA'



WHERE 
	MT.CODCOLIGADA = 3
AND GF.CODFILIAL IN(3,4,5,6,7,8,9,10,12,13,14,15)
AND MT.CODCURSO = '3101001'
--AND ST.DTFINAL >= '2018-01-01' AND ST.DTINICIAL <= '2018-31-01'