SELECT 
SUB.Unidade,
SUB.Modalidade,
SUB.Curso,
SUB.CodTurma,
SUB.DataInicio,
SUB.DataTermino,
SUB.Disciplina,
COUNT(RA) AS 'Matriculados'

FROM

(SELECT
	GFILIAL.NOMEFANTASIA AS 'Unidade',
	SMODALIDADECURSO.DESCRICAO AS 'Modalidade',
	SCURSO.NOME AS 'Curso',
	STURMA.CODTURMA AS 'CodTurma',
	CONVERT(VARCHAR(10),STURMA.DTINICIAL,103) AS 'DataInicio',
	CONVERT(VARCHAR(10),STURMA.DTFINAL,103) AS 'DataTermino',
	SDISCIPLINA.NOME AS 'Disciplina',
	SMATRICULA.RA,
	SMATRICULA.CODSTATUS
	
FROM

SMATRICULA

INNER JOIN STURMADISC ON 
	STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
	STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
INNER JOIN SDISCIPLINA ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
INNER JOIN STURMA ON 
	STURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND 
	STURMA.CODFILIAL = STURMADISC.CODFILIAL AND 
	STURMA.CODTURMA = STURMADISC.CODTURMA AND 
	STURMA.IDPERLET = STURMADISC.IDPERLET
	
INNER JOIN SMATRICPL ON 
	SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND 
	SMATRICPL.IDPERLET = SMATRICULA.IDPERLET AND 
	SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL AND 
	SMATRICPL.RA = SMATRICULA.RA
	
INNER JOIN SHABILITACAOFILIAL ON 
	SHABILITACAOFILIAL.CODCOLIGADA = STURMA.CODCOLIGADA AND 
	SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMA.IDHABILITACAOFILIAL
	
INNER JOIN SGRADE ON 
	SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND 
	SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO AND 
	SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO AND 
	SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
	
INNER JOIN SHABILITACAO ON 
	SHABILITACAO.CODCOLIGADA = SGRADE.CODCOLIGADA AND 
	SHABILITACAO.CODCURSO = SGRADE.CODCURSO AND 
	SHABILITACAO.CODHABILITACAO = SGRADE.CODHABILITACAO

INNER JOIN SCURSO ON 
	SCURSO.CODCOLIGADA = SHABILITACAO.CODCOLIGADA AND 
	SCURSO.CODCURSO = SHABILITACAO.CODCURSO

INNER JOIN SMODALIDADECURSO ON 
	SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA AND 
	SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO

INNER JOIN GFILIAL ON 
	STURMA.CODCOLIGADA = GFILIAL.CODCOLIGADA AND 
	STURMA.CODFILIAL = GFILIAL.CODFILIAL


WHERE
	STURMA.CODCOLIGADA = 3 AND
	STURMA.DTFINAL BETWEEN '2014-01-01' AND '2017-31-12')
SUB

WHERE SUB.CODSTATUS = 2
GROUP BY SUB.Unidade,SUB.Modalidade,SUB.Curso,SUB.CodTurma,SUB.DataInicio,SUB.DataTermino,SUB.Disciplina