SELECT 
TAB.NOMEFANTASIA,
TAB.CURSO,
TAB.DISCIPLINA,
TAB.RA,
TAB.ALUNO,
TAB.SITUACAO

 FROM (
SELECT
GFILIAL.NOMEFANTASIA,
SMODALIDADECURSO.DESCRICAO,
SCURSO.NOME AS 'CURSO',
SMA.RA,
PPESSOA.NOME AS 'ALUNO',
STURMADISC.CODTURMA,
SMATRICPL.PERIODO AS 'MÓDULO',
SDISCIPLINA.NOME AS 'DISCIPLINA',
CONVERT(VARCHAR,STURMADISC.DTINICIAL,103) AS 'DATA INICIAL',
CONVERT(VARCHAR,STURMADISC.DTFINAL,103)AS 'DATA FINAL',
SSTATUS.DESCRICAO AS 'SITUACAO',
STT.DESCRICAO AS 'SITUACAO NO CURSO'



FROM
SMATRICULA SMA

INNER JOIN  SMATRICPL 
ON SMATRICPL.CODCOLIGADA = SMA.CODCOLIGADA 
AND SMATRICPL.IDPERLET = SMA.IDPERLET 
AND SMATRICPL.IDHABILITACAOFILIAL = SMA.IDHABILITACAOFILIAL 
AND SMATRICPL.RA = SMA.RA

INNER JOIN SSTATUS 
ON SSTATUS.CODCOLIGADA = SMA.CODCOLIGADA 
AND SSTATUS.CODSTATUS = SMA.CODSTATUS



INNER JOIN GFILIAL ON
SMATRICPL.CODCOLIGADA = GFILIAL.CODCOLIGADA
AND SMATRICPL.CODFILIAL = GFILIAL.CODFILIAL

INNER JOIN STURMADISC 
ON STURMADISC.CODCOLIGADA = SMA.CODCOLIGADA 
AND STURMADISC.IDTURMADISC = SMA.IDTURMADISC

INNER JOIN SDISCIPLINA 
ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA 
AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC

INNER JOIN SHABILITACAOALUNO 
ON SHABILITACAOALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL 
AND SHABILITACAOALUNO.RA = SMATRICPL.RA

INNER JOIN SALUNO ON SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA AND SALUNO.RA = SHABILITACAOALUNO.RA
INNER JOIN PPESSOA ON PPESSOA.CODIGO = SALUNO.CODPESSOA

INNER JOIN SSTATUS STT 
ON STT.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
AND STT.CODSTATUS = SHABILITACAOALUNO.CODSTATUS

INNER JOIN SHABILITACAOFILIAL 

ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL

INNER JOIN SGRADE ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
INNER JOIN SCURSO ON SCURSO.CODCOLIGADA = SGRADE.CODCOLIGADA AND SCURSO.CODCURSO = SGRADE.CODCURSO
INNER JOIN SMODALIDADECURSO ON SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO

WHERE 
--SMA.RA = '0020920'

SMA.CODCOLIGADA = 3
AND SMODALIDADECURSO.CODMODALIDADECURSO  = 31
AND (STURMADISC.DTINICIAL < '2018-01-01' OR STURMADISC.DTINICIAL IS NULL)
) TAB
