SELECT 
DISTINCT
GFILIAL.NOMEFANTASIA AS 'UO',
SGRADECOMPL.CURSOSCOP AS 'Codigo_SMD',
SGRADE.CODGRADE AS 'Codigo_Produto',
SMODALIDADECURSO.DESCRICAO AS 'Tipo_de_Produto',
SCURSO.NOME AS 'Nome_do_Produto',
SHABILITACAOFILIAL.CODDEPARTAMENTO AS 'CR',
GDEPTO.NOME AS 'Centro_Responsabilidade'

FROM 

SCURSO

INNER JOIN SMODALIDADECURSO ON SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO
INNER JOIN SHABILITACAO ON SHABILITACAO.CODCOLIGADA = SCURSO.CODCOLIGADA AND SHABILITACAO.CODCURSO = SCURSO.CODCURSO
INNER JOIN SGRADE ON SGRADE.CODCOLIGADA = SHABILITACAO.CODCOLIGADA AND SGRADE.CODCURSO = SHABILITACAO.CODCURSO AND SGRADE.CODHABILITACAO = SHABILITACAO.CODHABILITACAO
INNER JOIN SGRADECOMPL ON SGRADECOMPL.CODCOLIGADA = SGRADE.CODCOLIGADA AND SGRADECOMPL.CODCURSO = SGRADE.CODCURSO AND SGRADECOMPL.CODHABILITACAO = SGRADE.CODHABILITACAO AND SGRADECOMPL.CODGRADE = SGRADE.CODGRADE
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = SGRADE.CODCOLIGADA AND SHABILITACAOFILIAL.CODCURSO = SGRADE.CODCURSO AND SHABILITACAOFILIAL.CODHABILITACAO = SGRADE.CODHABILITACAO AND SHABILITACAOFILIAL.CODGRADE = SGRADE.CODGRADE
INNER JOIN GDEPTO ON GDEPTO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND GDEPTO.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL AND GDEPTO.CODDEPARTAMENTO = SHABILITACAOFILIAL.CODDEPARTAMENTO
INNER JOIN GFILIAL ON GFILIAL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND GFILIAL.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL

WHERE 

SCURSO.CODCOLIGADA = 3