SELECT GFILIAL.NOMEFANTASIA, PPESSOA.NOME INSTRUTOR, SPLETIVO.CODPERLET, STURMADISC.CODTURMA,SDISCIPLINA.CH, SDISCIPLINA.NOME DISCIPLINA,      
       SDISCIPLINA.CODDISC, SCURSO.NOME CURSO, STURMADISC.DTINICIAL, STURMADISC.DTFINAL, SPROFESSOR.CHAPA, PFUNCAO.NOME FUNCAO
FROM   STURMADISC
       JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
       JOIN SCURSO ON SCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND SCURSO.CODCURSO=SHABILITACAOFILIAL.CODCURSO
       JOIN SDISCIPLINA ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC 
       JOIN SPLETIVO ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA AND SPLETIVO.IDPERLET=STURMADISC.IDPERLET 
       JOIN GFILIAL ON GFILIAL.CODCOLIGADA=SPLETIVO.CODCOLIGADA AND GFILIAL.CODFILIAL=SPLETIVO.CODFILIAL
       JOIN SPROFESSORTURMA ON SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
       JOIN SPROFESSOR ON SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA AND SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
       JOIN PPESSOA ON PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
       JOIN PFUNC ON PFUNC.CHAPA=SPROFESSOR.CHAPA AND PFUNC.CODCOLIGADA=SPROFESSOR.CODCOLIGADA
       JOIN PFUNCAO ON PFUNCAO.CODCOLIGADA=PFUNC.CODCOLIGADA AND PFUNCAO.CODIGO=PFUNC.CODFUNCAO
WHERE  /*SPLETIVO.CODPERLET IN ('HT2018','FIC2017')*/

 SPROFESSOR.CODPROF = '201'
AND STURMADISC.DTFINAL >= '2018-01-01'
ORDER BY GFILIAL.NOMEFANTASIA, PPESSOA.NOME