SELECT GFILIAL.NOMEFANTASIA,STURMA.CODTURMA FROM STURMA
INNER JOIN STURMACOMPL ON STURMACOMPL.CODCOLIGADA = STURMA.CODCOLIGADA AND STURMACOMPL.CODFILIAL = STURMA.CODFILIAL AND STURMACOMPL.CODTURMA = STURMA.CODTURMA AND STURMACOMPL.IDPERLET = STURMA.IDPERLET
INNER JOIN GFILIAL ON GFILIAL.CODCOLIGADA = STURMA.CODCOLIGADA AND GFILIAL.CODFILIAL  = STURMA.CODFILIAL

WHERE STURMA.CODCOLIGADA = 3
AND (STURMACOMPL.TRETIDA IS NULL OR STURMACOMPL.TRETIDA = 2)
AND (STURMA.CODTURMA LIKE '%RT%' OR STURMA.CODTURMA LIKE '%PEAD%')
AND STURMA.DTFINAL >= '2018-01-01'
