DECLARE @DATADE DATETIME
DECLARE @DATAATE DATETIME

SET @DATADE = '2017-01-12'
SET @DATAATE = '2017-31-12'

SELECT DISTINCT

SHABILITACAOALUNO.RA,
SHABILITACAOALUNOCOMPL.DATAINICIAL,
SHABILITACAOALUNOCOMPL.DATAFINAL,
SHABILITACAOALUNO.CODSTATUS


FROM SHABILITACAOALUNO 

INNER JOIN SHABILITACAOALUNOCOMPL ON 
	SHABILITACAOALUNOCOMPL.CODCOLIGADA 			= SHABILITACAOALUNO.CODCOLIGADA 
AND SHABILITACAOALUNOCOMPL.IDHABILITACAOFILIAL 	= SHABILITACAOALUNO.IDHABILITACAOFILIAL 
AND SHABILITACAOALUNOCOMPL.RA 					= SHABILITACAOALUNO.RA

INNER JOIN SMATRICPL ON 
	SMATRICPL.CODCOLIGADA 			= SHABILITACAOALUNO.CODCOLIGADA 
AND SMATRICPL.IDHABILITACAOFILIAL 	= SHABILITACAOALUNO.IDHABILITACAOFILIAL 
AND SMATRICPL.RA 					= SHABILITACAOALUNO.RA

INNER JOIN SMATRICPL SMP2 ON 
	SMATRICPL.CODCOLIGADA 			= SMP2.CODCOLIGADA 
AND SMATRICPL.IDHABILITACAOFILIAL 	= SMP2.IDHABILITACAOFILIAL 
AND SMATRICPL.RA 					= SMP2.RA



INNER JOIN SMATRICPLCOMPL ON 
	SMATRICPLCOMPL.CODCOLIGADA 			= SMATRICPL.CODCOLIGADA 
AND SMATRICPLCOMPL.IDPERLET 			= SMATRICPL.IDPERLET 
AND SMATRICPLCOMPL.IDHABILITACAOFILIAL 	= SMATRICPL.IDHABILITACAOFILIAL 
AND SMATRICPLCOMPL.RA 					= SMATRICPL.RA

INNER JOIN STURMA ON 
	STURMA.CODCOLIGADA 		= SMATRICPL.CODCOLIGADA 
AND STURMA.CODFILIAL 		= SMATRICPL.CODFILIAL 
AND STURMA.CODTURMA 		= SMATRICPL.CODTURMA 
AND STURMA.IDPERLET    		= SMATRICPL.IDPERLET

INNER JOIN STURMACOMPL ON 
	STURMACOMPL.CODCOLIGADA = STURMA.CODCOLIGADA 
AND STURMACOMPL.CODFILIAL 	= STURMA.CODFILIAL 
AND STURMACOMPL.CODTURMA 	= STURMA.CODTURMA 
AND STURMACOMPL.IDPERLET 	= STURMA.IDPERLET

WHERE SHABILITACAOALUNO.RA = '0028588'
AND (STURMA.DTINICIAL < @DATAATE AND STURMA.DTFINAL >= @DATADE)
AND (SHABILITACAOALUNOCOMPL.DATAINICIAL < @DATAATE AND SHABILITACAOALUNOCOMPL.DATAFINAL >= @DATADE)
AND (STURMACOMPL.TRETIDA != 1 OR STURMACOMPL.TRETIDA IS NULL)
AND (SMATRICPLCOMPL.ENVIAPROD != 2 OR SMATRICPLCOMPL.ENVIAPROD IS NULL )
