DECLARE @DATADE  DATETIME

SET @DATADE = '2018-01-01'

SELECT
DISTINCT
RESP.NOMEFANTASIA,
ST.CODTURMA,
RESP.CGCCFO AS 'CNPJ',
/*(SELECT COUNT(SMATRICPL.RA) FROM SMATRICPL

INNER JOIN STURMA ON STURMA.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND STURMA.CODFILIAL = SMATRICPL.CODFILIAL AND STURMA.CODTURMA = SMATRICPL.CODTURMA AND STURMA.IDPERLET = SMATRICPL.IDPERLET
INNER JOIN SCONTRATO ON SCONTRATO.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SCONTRATO.IDPERLET = SMATRICPL.IDPERLET AND SCONTRATO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL AND SCONTRATO.RA = SMATRICPL.RA
INNER JOIN SRESPONSAVELCONTRATO ON SRESPONSAVELCONTRATO.CODCOLIGADA = SCONTRATO.CODCOLIGADA AND SRESPONSAVELCONTRATO.RA = SCONTRATO.RA AND SRESPONSAVELCONTRATO.CODCONTRATO = SCONTRATO.CODCONTRATO AND SRESPONSAVELCONTRATO.IDPERLET = SCONTRATO.IDPERLET
INNER JOIN FCFO ON FCFO.CODCOLIGADA = SRESPONSAVELCONTRATO.CODCOLCFO AND FCFO.CODCFO = SRESPONSAVELCONTRATO.CODCFO

WHERE STURMA.CODTURMA = ST.CODTURMA AND
SMATRICPL.CODCOLIGADA = SMP.CODCOLIGADA AND
SMATRICPL.CODFILIAL = SMP.CODFILIAL) AS 'ATENDIDOS',*/
(SELECT COUNT(SMATRICPL.RA) FROM SMATRICPL

INNER JOIN STURMA ON STURMA.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND STURMA.CODFILIAL = SMATRICPL.CODFILIAL AND STURMA.CODTURMA = SMATRICPL.CODTURMA AND STURMA.IDPERLET = SMATRICPL.IDPERLET
INNER JOIN SCONTRATO ON SCONTRATO.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SCONTRATO.IDPERLET = SMATRICPL.IDPERLET AND SCONTRATO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL AND SCONTRATO.RA = SMATRICPL.RA
INNER JOIN SRESPONSAVELCONTRATO ON SRESPONSAVELCONTRATO.CODCOLIGADA = SCONTRATO.CODCOLIGADA AND SRESPONSAVELCONTRATO.RA = SCONTRATO.RA AND SRESPONSAVELCONTRATO.CODCONTRATO = SCONTRATO.CODCONTRATO AND SRESPONSAVELCONTRATO.IDPERLET = SCONTRATO.IDPERLET
INNER JOIN FCFO ON FCFO.CODCOLIGADA = SRESPONSAVELCONTRATO.CODCOLCFO AND FCFO.CODCFO = SRESPONSAVELCONTRATO.CODCFO

WHERE STURMA.CODTURMA = ST.CODTURMA AND
SMATRICPL.CODCOLIGADA = SMP.CODCOLIGADA AND
SMATRICPL.CODFILIAL = SMP.CODFILIAL AND 
--SMATRICPL.CODSTATUS != 2 AND
SCONTRATO.CODCONTRATO = SC.CODCONTRATO AND
SRESPONSAVELCONTRATO.CODCFO = SRC.CODCFO AND
FCFO.CGCCFO = RESP.CGCCFO) AS 'ATENDIDOS',
CONVERT(VARCHAR,SHABILITACAOALUNOCOMPL.DATAINICIAL,103) AS 'INICIO DO CONTRATO',
CONVERT(VARCHAR,SHABILITACAOALUNOCOMPL.DATAFINAL,103) AS 'TÉRMINO DO CONTRATO'

FROM SMATRICPL SMP

INNER JOIN SHABILITACAOALUNO SHA ON SHA.CODCOLIGADA = SMP.CODCOLIGADA AND SHA.IDHABILITACAOFILIAL = SMP.IDHABILITACAOFILIAL AND SHA.RA = SMP.RA
INNER JOIN SHABILITACAOALUNOCOMPL ON SHABILITACAOALUNOCOMPL.CODCOLIGADA = SHA.CODCOLIGADA AND SHABILITACAOALUNOCOMPL.IDHABILITACAOFILIAL = SHA.IDHABILITACAOFILIAL AND SHABILITACAOALUNOCOMPL.RA = SHA.RA
INNER JOIN STURMA  ST ON ST.CODCOLIGADA = SMP.CODCOLIGADA AND ST.CODFILIAL = SMP.CODFILIAL AND ST.CODTURMA = SMP.CODTURMA AND ST.IDPERLET = SMP.IDPERLET
INNER JOIN SCONTRATO SC ON SC.CODCOLIGADA = SMP.CODCOLIGADA AND SC.IDPERLET = SMP.IDPERLET AND SC.IDHABILITACAOFILIAL = SC.IDHABILITACAOFILIAL AND SC.RA = SMP.RA
INNER JOIN SRESPONSAVELCONTRATO SRC ON SRC.CODCOLIGADA = SC.CODCOLIGADA AND SRC.RA = SC.RA AND SRC.CODCONTRATO = SC.CODCONTRATO AND SRC.IDPERLET = SC.IDPERLET
INNER JOIN FCFO RESP ON RESP.CODCOLIGADA = SRC.CODCOLCFO AND RESP.CODCFO = SRC.CODCFO
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.CODCOLIGADA = SHA.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHA.IDHABILITACAOFILIAL
INNER JOIN SGRADE ON SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
INNER JOIN SHABILITACAO ON SHABILITACAO.CODCOLIGADA = SGRADE.CODCOLIGADA AND SHABILITACAO.CODCURSO = SGRADE.CODCURSO AND SHABILITACAO.CODHABILITACAO = SGRADE.CODHABILITACAO
INNER JOIN SCURSO ON SCURSO.CODCOLIGADA = SHABILITACAO.CODCOLIGADA AND SCURSO.CODCURSO = SHABILITACAO.CODCURSO
INNER JOIN SMODALIDADECURSO ON SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO

WHERE SHABILITACAOALUNOCOMPL.DATAINICIAL >= @DATADE AND
SMP.CODCOLIGADA = 3 AND
SMP.CODFILIAL = 4 AND 
SMODALIDADECURSO.CODMODALIDADECURSO IN ('11','15') AND
RESP.CGCCFO = '30.679.310/0001-45'