
/*
ULTIMA ALTERAÇÃO - 04/08/2016 - Allan Cavalcante - DTI - Incluído ; antes do WITH
ULTIMA ALTERAÇÃO - 07/04/2017 - Juliana Harduim inserido o status 47 na situacao e tambem para sair com asterisco
ULTIMA ALTERACAO - 07/04/2017 - Joao Marcos - inclusao do campo HORINI para compor a Data do plano de aula
ULTIMA ALTERACAO - 14/12/2017 - Joao Marcos - inclusao do CONCAT para formatar as datas com a HORINI do turno
											- inclusao do MAX(CODSTATUS) IS NULL para colocar asterisco quando nao ha ultima alteracao com base em uma data de aula
ULTIMA ALTERACAO - 20/12/2017 - Joao Marcos - alteracao do MAX(CODSTATUS) IS NULL para um clausula especifica, para inserir o valor F nestes casos
ULTIMA ALTERACAO - 21/12/2017 - Joao Marcos - exclusão do MAX(CODSTATUS) IS NULL para não inserir o valor F automaticamente nos casos que o aluno foi matriculado após o início da turma
*/
DECLARE @IDTURMADISC INT,@CODCOLIGADA INT,@INICIO INT, @FINAL INT,@QTDE INT, @FATORPAG INT
 
SET @CODCOLIGADA = :P_CODCOLIGADA_N
SET @IDTURMADISC = :P_IDTURMADISC_N
SET @INICIO = 1
SET @FINAL = 25
SET @QTDE = (     SELECT 
         COUNT(SMATRICULA.RA) AS QTDE        
         FROM SMATRICULA (NOLOCK)
         WHERE SMATRICULA.CODCOLIGADA = @CODCOLIGADA
         AND SMATRICULA.IDTURMADISC = @IDTURMADISC
   )

DECLARE @codetapaIni NVARCHAR(2)
DECLARE @codetapaFim NVARCHAR(2)
DECLARE @codigoEtapa NVARCHAR(10)
DECLARE @dataIni DATETIME 
DECLARE @dataFim DATETIME

SET @codigoEtapa = :P_CODETAPA

if(@codigoEtapa is null or @codigoEtapa = '') begin
	SET @dataIni = CONVERT(DATETIME,:DTINICIO,103)
	SET @dataFim = CONVERT(DATETIME,:DTFIM,103) 
	
	end
	
else begin
	if(len(@codigoEtapa)=1 and @codigoEtapa <> '-') begin
		set @codetapaIni = @codigoEtapa 
		SET @dataIni = (SELECT dtinicio FROM SETAPAS WHERE codcoligada = @codColigada
	   					AND idturmadisc = @idturmaDisc AND codetapa = @codetapaIni
	   					AND tipoetapa = 'F')
	   	SET @dataFim = (SELECT dtfim FROM SETAPAS WHERE codcoligada = @codColigada
	   					AND idturmadisc = @idturmaDisc AND codetapa = @codetapaIni
	   					AND tipoetapa = 'F') end
	
	else if(len(@codigoEtapa) = 2 AND SUBSTRING(@codigoEtapa,2,2) = '-') begin
		SET @codetapaIni = substring(@codigoEtapa,1,1) 
		SET @dataIni = (SELECT dtinicio FROM SETAPAS WHERE codcoligada = @codColigada
	   					AND idturmadisc = @idturmaDisc AND codetapa = @codetapaIni
	   					AND tipoetapa = 'F')
	   	SET @dataFim = (SELECT dtfim FROM SETAPAS WHERE codcoligada = @codColigada
	   					AND idturmadisc = @idturmaDisc AND codetapa = @codetapaIni
	   					AND tipoetapa = 'F') end
		
	else  if (len(@codigoEtapa) = 2 AND SUBSTRING(@codigoEtapa,2,2) <> '-') begin
		SET @codetapaIni = @codigoEtapa 
		SET @dataIni = (SELECT dtinicio FROM SETAPAS WHERE codcoligada = @codColigada
	   					AND idturmadisc = @idturmaDisc AND codetapa = @codetapaIni
	   					AND tipoetapa = 'F')
	   	SET @dataFim = (SELECT dtfim FROM SETAPAS WHERE codcoligada = @codColigada
	   					AND idturmadisc = @idturmaDisc AND codetapa = @codetapaIni
	   					AND tipoetapa = 'F') END
	   					
	else if (len(@codigoEtapa) > 2) begin

		if (len(@codigoEtapa) = 3) begin
			if(substring(@codigoEtapa,2,1) = '-')begin
				set @codetapaIni = substring(@codigoEtapa,1,1)
				set @codetapaFim = substring(@codigoEtapa,3,1) end
			else if (substring(@codigoEtapa,3,1) = '-')begin
				set @codetapaIni = substring(@codigoEtapa,1,2)
				set @codetapaFim = '' end
		end
		else if(len(@codigoEtapa) = 4) begin
			if(substring(@codigoEtapa,2,1) = '-')begin
				set @codetapaIni = substring(@codigoEtapa,1,1)
				SET @codetapaFim = substring(@codigoEtapa,3,2) end 
			ELSE IF (substring(@codigoEtapa,3,1) = '-')begin
				set @codetapaIni = substring(@codigoEtapa,1,2)
				SET @codetapaFim = substring(@codigoEtapa,4,1) end	
		end
		else if(len(@codigoEtapa) = 5) begin
				set @codetapaIni = substring(@codigoEtapa,1,2)
				SET @codetapaFim = substring(@codigoEtapa,4,2) end 
	
		
		if (@codetapaFim IS NULL OR @codetapaFim = '') begin 
			   	set @dataIni = (SELECT dtinicio FROM SETAPAS WHERE codcoligada = @codColigada
			   					AND idturmadisc = @idturmaDisc AND codetapa = @codetapaIni
			   					AND tipoetapa = 'F')
			   	set @dataFim = (SELECT dtfim FROM SETAPAS WHERE codcoligada = @codColigada
			   					AND idturmadisc = @idturmaDisc AND codetapa = @codetapaIni
			   					AND tipoetapa = 'F') end
		else begin
				set @dataIni = (SELECT dtinicio FROM SETAPAS WHERE codcoligada = @codColigada
								AND idturmadisc = @idturmaDisc AND codetapa = @codetapaIni
								AND tipoetapa = 'F')
				set @dataFim = (SELECT dtfim FROM SETAPAS WHERE codcoligada = @codColigada
								AND idturmadisc = @idturmaDisc AND codetapa = @codetapaFim
							    AND tipoetapa = 'F') end 
	end
end

SET @FATORPAG = CEILING(@QTDE/@FINAL);

WITH NUMEROS (NUM) AS (
SELECT 0 UNION ALL
SELECT 1 UNION ALL
SELECT 2 UNION ALL
SELECT 3 UNION ALL
SELECT 4 UNION ALL
SELECT 5 UNION ALL
SELECT 6 UNION ALL
SELECT 7 UNION ALL
SELECT 8 UNION ALL
SELECT 9 ),
RANGETOTAL (VAL) AS (
SELECT ROW_NUMBER() OVER (ORDER BY N1.NUM ASC) AS NUMERO
FROM NUMEROS AS N1, NUMEROS AS N2, NUMEROS AS N3)
SELECT  0 CONTADOR,
  2 ORDENADOR,
  CASE WHEN @QTDE<=@FINAL THEN 1 
    WHEN @QTDE>@FINAL THEN  CEILING((ROW_NUMBER() OVER (ORDER BY VAL) + @QTDE) / (@FINAL * 1.0)) END  PAGALUNOS, 
  :PAGINA21 PAGINA2,
  NULL ORDEM,
  NULL RA, 
  NULL ALUNO,
  NULL SITUACAO,
  NULL FALTAS,
  NULL FREQ1,
  NULL FREQ2,
  NULL FREQ3,
  NULL FREQ4,
  NULL FREQ5,
  NULL FREQ6,
  NULL FREQ7,
  NULL FREQ8,
  NULL FREQ9,
  NULL FREQ10,
  NULL FREQ11,
  NULL FREQ12,
  NULL FREQ13,
  NULL FREQ14,
  NULL FREQ15,
  NULL FREQ16,
  NULL FREQ17,
  NULL FREQ18,
  NULL FREQ19,
  NULL FREQ20,
  NULL FREQ21,
  NULL FREQ22,
  NULL FREQ23,
  NULL FREQ24,
  NULL FREQ25,
  NULL FREQ26,
  NULL FREQ27,
  NULL FREQ28,
  NULL FREQ29,
  NULL FREQ30,
  NULL FREQ31,
  NULL FREQ32,
  NULL FREQ33,
  NULL FREQ34,
  NULL FREQ35,
  NULL FREQ36,
  NULL FREQ37,
  NULL FREQ38,
  NULL FREQ39,
  NULL FREQ40
  
FROM RANGETOTAL
WHERE  VAL <= CASE WHEN (@FINAL >  @QTDE)  THEN @FINAL - @QTDE
                   WHEN (@FINAL * @FATORPAG) = @QTDE THEN 0
       ELSE (@FINAL * @FATORPAG) - (@QTDE - @FINAL)  END

UNION ALL


SELECT 1 CONTADOR,
  1 ORDENADOR,
  CASE WHEN @QTDE <= @FINAL THEN 1 
       WHEN @QTDE>@FINAL THEN  CEILING((ROW_NUMBER() OVER (ORDER BY PPESSOA.NOME)) / (@FINAL * 1.0)) END PAGALUNOS,
  :PAGINA21 PAGINA2,
  ROW_NUMBER() OVER (ORDER BY PPESSOA.NOME) /*SMATRICULA.NUMDIARIO esta parte enumera alunos entrando depois do inicio da turma para o final */ ORDEM,
  SMATRICPL.RA,
  PPESSOA.NOME ALUNO,
  CASE
  WHEN SSTATUS.CODSTATUS = 3 THEN 'C'
  WHEN SSTATUS.CODSTATUS = 5 THEN 'E'
  WHEN SSTATUS.CODSTATUS = 1 THEN 'P'
  WHEN SSTATUS.CODSTATUS = 47 THEN 'D' /* incluido este status por Juliana 07/04/2017 */
  WHEN SSTATUS.CODSTATUS IN (4,8)  THEN 'T'
  WHEN SSTATUS.CODSTATUS IN (13,20,10,2,16,43)  THEN 'M'
 END  SITUACAO,
  CONVERT(INT,ISNULL(FREQUENCIA.FALTAS,0)) FALTAS,


(
     SELECT 
     CASE 
      WHEN :P_DATA1_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ1,CASE WHEN :P_AULA1_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA1_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA1_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)as FREQ1,
	

(
 SELECT 
     CASE 
      WHEN :P_DATA2_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ2,CASE WHEN :P_AULA2_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA2_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA2_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  AS FREQ2,
(
 SELECT 
     CASE 
      WHEN :P_DATA3_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ3,CASE WHEN :P_AULA3_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA3_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA3_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  AS FREQ3,
(
 SELECT 
     CASE 
      WHEN :P_DATA4_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ4,CASE WHEN :P_AULA4_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA4_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA4_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  AS FREQ4,
(
 SELECT 
     CASE 
      WHEN :P_DATA5_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ5,CASE WHEN :P_AULA5_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA5_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA5_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  AS FREQ5,
(
 SELECT 
     CASE 
      WHEN :P_DATA6_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ6,CASE WHEN :P_AULA6_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA6_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA6_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  AS FREQ6,
(
 SELECT 
     CASE 
      WHEN :P_DATA7_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ7,CASE WHEN :P_AULA7_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA7_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA7_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  AS FREQ7,
( 
 SELECT 
     CASE 
      WHEN :P_DATA8_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ8,CASE WHEN :P_AULA8_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA8_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA8_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
 )  AS FREQ8,
 (
  SELECT 
     CASE
      WHEN :P_DATA9_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ9,CASE WHEN :P_AULA9_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA9_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA9_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
 )  AS FREQ9,

 (
  SELECT 
     CASE 
      WHEN :P_DATA10_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ10,CASE WHEN :P_AULA10_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA10_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA10_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
 )  AS FREQ10,
(
  SELECT 
    CASE 
      WHEN :P_DATA11_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ11,CASE WHEN :P_AULA11_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA11_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA11_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ11,
(
  SELECT 
    CASE 
      WHEN :P_DATA12_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ12,CASE WHEN :P_AULA12_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA12_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA12_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ12,
(
  SELECT 
    CASE  
      WHEN :P_DATA13_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ13,CASE WHEN :P_AULA13_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA13_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA13_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ13,
(
  SELECT 
    CASE 
      WHEN :P_DATA14_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ14,CASE WHEN :P_AULA14_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA14_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA14_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ14,
(
  SELECT 
    CASE  
      WHEN :P_DATA15_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ15,CASE WHEN :P_AULA15_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA15_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA15_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ15,

(
  SELECT 
    CASE 
      WHEN :P_DATA16_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ16,CASE WHEN :P_AULA16_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA16_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA16_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ16,
(
  SELECT  
 CASE
      WHEN :P_DATA17_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ17,CASE WHEN :P_AULA17_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA17_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA17_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ17,
(
  SELECT 
    CASE 
      WHEN :P_DATA18_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ18,CASE WHEN :P_AULA18_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA18_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA18_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ18,
(
  SELECT 
    CASE 
      WHEN :P_DATA19_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ19,CASE WHEN :P_AULA19_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA19_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA19_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ19,
(
  SELECT 
    CASE 
      WHEN :P_DATA20_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ20,CASE WHEN :P_AULA20_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA20_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA20_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ20,
(
  SELECT 
    CASE 
      WHEN :P_DATA21_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ21,CASE WHEN :P_AULA21_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA21_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA21_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ21,
(
  SELECT 
    CASE 
      WHEN :P_DATA22_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ22,CASE WHEN :P_AULA22_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA22_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA22_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
 )  as FREQ22,
(
  SELECT 
    CASE 
      WHEN :P_DATA23_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ23,CASE WHEN :P_AULA23_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA23_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA23_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ23,
(
  SELECT 
    CASE 
      WHEN :P_DATA24_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ24,CASE WHEN :P_AULA24_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA24_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA24_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ24,
(
  SELECT 
    CASE 
      WHEN :P_DATA25_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ25,CASE WHEN :P_AULA25_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA25_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA25_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ25,
(
 SELECT 
    CASE 
      WHEN :P_DATA26_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ26,CASE WHEN :P_AULA26_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA26_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA26_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ26,
(
 SELECT 
    CASE 
      WHEN :P_DATA27_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ27,CASE WHEN :P_AULA27_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA27_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA27_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ27,
(
 SELECT 
    CASE 
      WHEN :P_DATA28_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ28,CASE WHEN :P_AULA28_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA28_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA28_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ28,
(
 SELECT 
    CASE 
      WHEN :P_DATA29_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ29,CASE WHEN :P_AULA29_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA29_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA29_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ29,
(
 SELECT 
    CASE 
      WHEN :P_DATA30_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ30,CASE WHEN :P_AULA30_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA30_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA30_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ30,
(
 SELECT 
    CASE 
      WHEN :P_DATA31_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ31,CASE WHEN :P_AULA31_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA31_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA31_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ31,
(
 SELECT 
    CASE 
      WHEN :P_DATA32_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ32,CASE WHEN :P_AULA32_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA32_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA32_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
 )  as FREQ32,
(
 SELECT 
    CASE 
      WHEN :P_DATA33_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ33,CASE WHEN :P_AULA33_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA33_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA33_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ33,
 (
 SELECT 
    CASE 
      WHEN :P_DATA34_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ34,CASE WHEN :P_AULA34_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA34_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA34_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA 
 )  as FREQ34,
 (
 SELECT 
    CASE 
      WHEN :P_DATA35_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ35,CASE WHEN :P_AULA35_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA35_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA35_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
 )  as FREQ35,
 (
  SELECT 
    CASE 
      WHEN :P_DATA36_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ36,CASE WHEN :P_AULA36_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA36_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA36_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
 )  as FREQ36,
(
 SELECT 
    CASE 
      WHEN :P_DATA37_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ37,CASE WHEN :P_AULA37_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA37_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA37_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
)  as FREQ37,

 (
  SELECT 
    CASE 
      WHEN :P_DATA38_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ38,CASE WHEN :P_AULA38_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA38_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA38_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
 )  as FREQ38,
 (
  SELECT 
    CASE 
      WHEN :P_DATA39_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ39,CASE WHEN :P_AULA39_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA39_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA39_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
 )  as FREQ39,
 (
  SELECT 
    CASE 
      WHEN :P_DATA40_N  IS NULL THEN ''
      WHEN MAX(CODSTATUS) IN (1,3,4,5,6,7,8,9,47) THEN '*' 
      ELSE ISNULL(AUSENTE.FREQ40,CASE WHEN :P_AULA40_N  IS NOT NULL THEN '.' END) 
     END AS COL
     FROM SLOGMATRICULA (NOLOCK)
     INNER JOIN 
     (
      SELECT
          MAX(DTALTERACAO)DATA, RA, CODCOLIGADA
      FROM SLOGMATRICULA (NOLOCK)
      WHERE RA=SMATRICULA.RA
      AND CODCOLIGADA = SMATRICULA.CODCOLIGADA
      AND IDTURMADISC=SMATRICULA.IDTURMADISC
      
      AND DTALTERACAO <= CONCAT(:P_DATA40_D,' ',:HORINI) /*AND DTALTERACAO < = :P_DATA40_D*/
      GROUP BY RA, CODCOLIGADA
     )AUX
     ON  SLOGMATRICULA.CODCOLIGADA = AUX.CODCOLIGADA
     AND SLOGMATRICULA.RA   = AUX.RA
     AND SLOGMATRICULA.DTALTERACAO = AUX.DATA
 )  as FREQ40

FROM SMATRICULA(NOLOCK)
INNER JOIN SMATRICPL(NOLOCK)
  ON SMATRICPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
  AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
  AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
  AND SMATRICPL.RA = SMATRICULA.RA
INNER JOIN SMATRICPLCOMPL(NOLOCK)
  ON SMATRICPL.CODCOLIGADA = SMATRICPLCOMPL.CODCOLIGADA
  AND SMATRICPL.IDPERLET = SMATRICPLCOMPL.IDPERLET
  AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICPLCOMPL.IDHABILITACAOFILIAL
  AND SMATRICPL.RA = SMATRICPLCOMPL.RA
INNER JOIN SMATRICULACOMPL(NOLOCK)
  ON SMATRICULACOMPL.CODCOLIGADA = SMATRICULA.CODCOLIGADA
  AND SMATRICULACOMPL.IDTURMADISC = SMATRICULA.IDTURMADISC
  AND SMATRICULACOMPL.RA = SMATRICULA.RA  
INNER JOIN SALUNO(NOLOCK)
  ON SALUNO.CODCOLIGADA = SMATRICULA.CODCOLIGADA
  AND SALUNO.RA = SMATRICULA.RA
INNER JOIN PPESSOA(NOLOCK)
  ON PPESSOA.CODIGO = SALUNO.CODPESSOA
INNER JOIN STURMADISC(NOLOCK)
  ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
  AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
INNER JOIN SDISCIPLINA(NOLOCK)
  ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
  AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
INNER JOIN SSTATUS(NOLOCK)
  ON SSTATUS.CODCOLIGADA = SMATRICULA.CODCOLIGADA
  AND SSTATUS.CODSTATUS = SMATRICULA.CODSTATUS
LEFT JOIN 
 ( SELECT SFREQUENCIA.CODCOLIGADA,
    SFREQUENCIA.IDTURMADISC,
    SFREQUENCIA.RA,
       MAX(CASE WHEN AULA = :P_AULA1_N AND SFREQUENCIA.DATA= :P_DATA1_D THEN 'F' END) FREQ1,
       MAX(CASE WHEN AULA = :P_AULA2_N AND SFREQUENCIA.DATA= :P_DATA2_D THEN 'F' END) FREQ2,
       MAX(CASE WHEN AULA = :P_AULA3_N AND SFREQUENCIA.DATA= :P_DATA3_D THEN 'F' END) FREQ3,
       MAX(CASE WHEN AULA = :P_AULA4_N AND SFREQUENCIA.DATA= :P_DATA4_D THEN 'F' END) FREQ4,
       MAX(CASE WHEN AULA = :P_AULA5_N AND SFREQUENCIA.DATA= :P_DATA5_D THEN 'F' END) FREQ5,
       MAX(CASE WHEN AULA = :P_AULA6_N AND SFREQUENCIA.DATA= :P_DATA6_D THEN 'F' END) FREQ6,
       MAX(CASE WHEN AULA = :P_AULA7_N AND SFREQUENCIA.DATA= :P_DATA7_D THEN 'F' END) FREQ7,
       MAX(CASE WHEN AULA = :P_AULA8_N AND SFREQUENCIA.DATA= :P_DATA8_D THEN 'F' END) FREQ8,
       MAX(CASE WHEN AULA = :P_AULA9_N AND SFREQUENCIA.DATA= :P_DATA9_D THEN 'F' END) FREQ9,
       MAX(CASE WHEN AULA = :P_AULA10_N AND SFREQUENCIA.DATA= :P_DATA10_D THEN 'F' END) FREQ10,
       MAX(CASE WHEN AULA = :P_AULA11_N AND SFREQUENCIA.DATA= :P_DATA11_D THEN 'F' END) FREQ11,
       MAX(CASE WHEN AULA = :P_AULA12_N AND SFREQUENCIA.DATA= :P_DATA12_D THEN 'F' END) FREQ12,
       MAX(CASE WHEN AULA = :P_AULA13_N AND SFREQUENCIA.DATA= :P_DATA13_D THEN 'F' END) FREQ13,
       MAX(CASE WHEN AULA = :P_AULA14_N AND SFREQUENCIA.DATA= :P_DATA14_D THEN 'F' END) FREQ14,
       MAX(CASE WHEN AULA = :P_AULA15_N AND SFREQUENCIA.DATA= :P_DATA15_D THEN 'F' END) FREQ15,
       MAX(CASE WHEN AULA = :P_AULA16_N AND SFREQUENCIA.DATA= :P_DATA16_D THEN 'F' END) FREQ16,
       MAX(CASE WHEN AULA = :P_AULA17_N AND SFREQUENCIA.DATA= :P_DATA17_D THEN 'F' END) FREQ17,
       MAX(CASE WHEN AULA = :P_AULA18_N AND SFREQUENCIA.DATA= :P_DATA18_D THEN 'F' END) FREQ18,
       MAX(CASE WHEN AULA = :P_AULA19_N AND SFREQUENCIA.DATA= :P_DATA19_D THEN 'F' END) FREQ19,
       MAX(CASE WHEN AULA = :P_AULA20_N AND SFREQUENCIA.DATA= :P_DATA20_D THEN 'F' END) FREQ20,
       MAX(CASE WHEN AULA = :P_AULA21_N AND SFREQUENCIA.DATA= :P_DATA21_D THEN 'F' END) FREQ21,
       MAX(CASE WHEN AULA = :P_AULA22_N AND SFREQUENCIA.DATA= :P_DATA22_D THEN 'F' END) FREQ22,
       MAX(CASE WHEN AULA = :P_AULA23_N AND SFREQUENCIA.DATA= :P_DATA23_D THEN 'F' END) FREQ23,
       MAX(CASE WHEN AULA = :P_AULA24_N AND SFREQUENCIA.DATA= :P_DATA24_D THEN 'F' END) FREQ24,
       MAX(CASE WHEN AULA = :P_AULA25_N AND SFREQUENCIA.DATA= :P_DATA25_D THEN 'F' END) FREQ25,
       MAX(CASE WHEN AULA = :P_AULA26_N AND SFREQUENCIA.DATA= :P_DATA26_D THEN 'F' END) FREQ26,
       MAX(CASE WHEN AULA = :P_AULA27_N AND SFREQUENCIA.DATA= :P_DATA27_D THEN 'F' END) FREQ27, 
       MAX(CASE WHEN AULA = :P_AULA28_N AND SFREQUENCIA.DATA= :P_DATA28_D THEN 'F' END) FREQ28,
       MAX(CASE WHEN AULA = :P_AULA29_N AND SFREQUENCIA.DATA= :P_DATA29_D THEN 'F' END) FREQ29,
       MAX(CASE WHEN AULA = :P_AULA30_N AND SFREQUENCIA.DATA= :P_DATA30_D THEN 'F' END) FREQ30,
       MAX(CASE WHEN AULA = :P_AULA31_N AND SFREQUENCIA.DATA= :P_DATA31_D THEN 'F' END) FREQ31,
       MAX(CASE WHEN AULA = :P_AULA32_N AND SFREQUENCIA.DATA= :P_DATA32_D THEN 'F' END) FREQ32,
       MAX(CASE WHEN AULA = :P_AULA33_N AND SFREQUENCIA.DATA= :P_DATA33_D THEN 'F' END) FREQ33,
       MAX(CASE WHEN AULA = :P_AULA34_N AND SFREQUENCIA.DATA= :P_DATA34_D THEN 'F' END) FREQ34,
       MAX(CASE WHEN AULA = :P_AULA35_N AND SFREQUENCIA.DATA= :P_DATA35_D THEN 'F' END) FREQ35,
       MAX(CASE WHEN AULA = :P_AULA36_N AND SFREQUENCIA.DATA= :P_DATA36_D THEN 'F' END) FREQ36, 
       MAX(CASE WHEN AULA = :P_AULA37_N AND SFREQUENCIA.DATA= :P_DATA37_D THEN 'F' END) FREQ37,
       MAX(CASE WHEN AULA = :P_AULA38_N AND SFREQUENCIA.DATA= :P_DATA38_D THEN 'F' END) FREQ38,
       MAX(CASE WHEN AULA = :P_AULA39_N AND SFREQUENCIA.DATA= :P_DATA39_D THEN 'F' END) FREQ39,
       MAX(CASE WHEN AULA = :P_AULA40_N AND SFREQUENCIA.DATA= :P_DATA40_D THEN 'F' END) FREQ40

  FROM SFREQUENCIA(NOLOCK)
  INNER JOIN SPLANOAULA(NOLOCK)
    ON SPLANOAULA.CODCOLIGADA = SFREQUENCIA.CODCOLIGADA
    AND SPLANOAULA.IDHORARIOTURMA = SFREQUENCIA.IDHORARIOTURMA
    AND SPLANOAULA.IDTURMADISC = SFREQUENCIA.IDTURMADISC
    AND SPLANOAULA.DATA = SFREQUENCIA.DATA
 GROUP BY    SFREQUENCIA.CODCOLIGADA,
    SFREQUENCIA.IDTURMADISC,
    SFREQUENCIA.RA
 ) AUSENTE
 ON  AUSENTE.CODCOLIGADA = SMATRICULA.CODCOLIGADA
 AND AUSENTE.IDTURMADISC = SMATRICULA.IDTURMADISC
 AND AUSENTE.RA = SMATRICULA.RA
LEFT JOIN 

  ( SELECT SFREQUENCIA.RA,
     COUNT(*) FALTAS
   FROM SFREQUENCIA(NOLOCK)
     INNER JOIN SHORARIOTURMA(NOLOCK)
       ON SHORARIOTURMA.CODCOLIGADA = SFREQUENCIA.CODCOLIGADA
       AND SHORARIOTURMA.IDHORARIOTURMA = SFREQUENCIA.IDHORARIOTURMA
     INNER JOIN SHORARIOPROFESSOR(NOLOCK)
       ON SHORARIOTURMA.CODCOLIGADA = SHORARIOPROFESSOR.CODCOLIGADA
       AND SHORARIOTURMA.IDHORARIOTURMA = SHORARIOPROFESSOR.IDHORARIOTURMA
     WHERE SFREQUENCIA.CODCOLIGADA = @CODCOLIGADA
     AND SFREQUENCIA.IDTURMADISC = @IDTURMADISC
     AND SHORARIOPROFESSOR.IDPROFESSORTURMA = :P_IDPROFESSORTURMA_N
     AND SFREQUENCIA.DATA BETWEEN @dataIni AND @dataFim
     GROUP BY SFREQUENCIA.RA
  ) FREQUENCIA
 ON FREQUENCIA.RA = SMATRICULA.RA
  

WHERE SMATRICULA.CODCOLIGADA = @CODCOLIGADA
AND SMATRICULA.IDTURMADISC =  @IDTURMADISC
AND SSTATUS.DESCRICAO NOT IN ('PRÉ-MATRICULADO')


ORDER BY 2,5
