SELECT 
SHABILITACAOALUNOCOMPL.RA,
SHABILITACAOALUNOCOMPL.DATAINICIAL,
SHABILITACAOALUNOCOMPL.DATAFINAL,
SHABILITACAOALUNOCOMPL.IDHABILITACAOFILIAL
FROM 

SHABILITACAOALUNOCOMPL

INNER JOIN SHABILITACAOALUNO ON
	SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOALUNOCOMPL.CODCOLIGADA 
AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOALUNOCOMPL.IDHABILITACAOFILIAL 
AND SHABILITACAOALUNO.RA = SHABILITACAOALUNOCOMPL.RA

INNER JOIN SMATRICPL ON
	SMATRICPL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
AND SMATRICPL.RA = SHABILITACAOALUNO.RA

INNER JOIN STURMA ON 
	STURMA.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
AND STURMA.CODFILIAL = SMATRICPL.CODFILIAL 
AND STURMA.CODTURMA = SMATRICPL.CODTURMA 
AND STURMA.IDPERLET = SMATRICPL.IDPERLET

WHERE

    STURMA.CODTURMA    			= 'COM-ALASER-8'
AND STURMA.CODFILIAL 			= 3
AND STURMA.CODCOLIGADA 			= 3
AND STURMA.IDHABILITACAOFILIAL 	= 6934