UPDATE 

SHABILITACAOALUNOCOMPL
SET
SHABILITACAOALUNOCOMPL.DATAINICIAL = :datainicial ,
SHABILITACAOALUNOCOMPL.DATAFINAL = :datafinal

FROM 

SHABILITACAOALUNOCOMPL

INNER JOIN SHABILITACAOALUNO ON
	SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOALUNOCOMPL.CODCOLIGADA 
AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOALUNOCOMPL.IDHABILITACAOFILIAL 
AND SHABILITACAOALUNO.RA = SHABILITACAOALUNOCOMPL.RA

INNER JOIN SMATRICPL ON
	SMATRICPL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
AND SMATRICPL.RA = SHABILITACAOALUNO.RA

INNER JOIN STURMA ON 
	STURMA.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
AND STURMA.CODFILIAL = SMATRICPL.CODFILIAL 
AND STURMA.CODTURMA = SMATRICPL.CODTURMA 
AND STURMA.IDPERLET = SMATRICPL.IDPERLET

WHERE

<<<<<<< HEAD
    STURMA.CODTURMA    			= 'COM-ALASER-8'
AND STURMA.CODFILIAL 			= 3
AND STURMA.CODCOLIGADA 			= 3
AND STURMA.IDHABILITACAOFILIAL 	= 6934
=======
    STURMA.CODTURMA = :codturma
AND STURMA.CODFILIAL = :codfilial
AND STURMA.CODCOLIGADA = :codcoligada
AND STURMA.IDHABILITACAOFILIAL = :idhabilitacaofilial
>>>>>>> 5a94a6ec5f6e6186a57609df4625c9f2bb71a214
