UPDATE 

SHABILITACAOALUNOCOMPL
SET
SHABILITACAOALUNOCOMPL.DATAINICIAL = :datainicial ,
SHABILITACAOALUNOCOMPL.DATAFINAL = :datafinal

FROM 

SHABILITACAOALUNOCOMPL

INNER JOIN SHABILITACAOALUNO ON
	SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOALUNOCOMPL.CODCOLIGADA 
AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOALUNOCOMPL.IDHABILITACAOFILIAL 
AND SHABILITACAOALUNO.RA = SHABILITACAOALUNOCOMPL.RA

INNER JOIN SMATRICPL ON
	SMATRICPL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA 
AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL 
AND SMATRICPL.RA = SHABILITACAOALUNO.RA

INNER JOIN STURMA ON 
	STURMA.CODCOLIGADA = SMATRICPL.CODCOLIGADA 
AND STURMA.CODFILIAL = SMATRICPL.CODFILIAL 
AND STURMA.CODTURMA = SMATRICPL.CODTURMA 
AND STURMA.IDPERLET = SMATRICPL.IDPERLET

WHERE

    STURMA.CODTURMA = :codturma
AND STURMA.CODFILIAL = :codfilial
AND STURMA.CODCOLIGADA = :codcoligada
AND STURMA.IDHABILITACAOFILIAL = :idhabilitacaofilial